services:
  postgres:
    image: postgres:17-alpine
    container_name: modalink-db
    environment:
      POSTGRES_DB: modalink
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docs/3_diseño/ModaLinkBD.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
