spring.datasource.url=jdbc:postgresql://localhost:5432/proyectoMVP
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.generate-ddl=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation= true

# Server
server.port=8080

# Para que haga las conversiones necesarias de HTML
spring.mvc.hiddenmethod.filter.enabled=true

# Cositas para FlyWay
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
export DB_PASSWORD=tu_password_local