spring.datasource.url=jdbc:postgresql://localhost:5432/modalink
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Server
server.port=8080

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.flyway.schemas=public
spring.flyway.baseline-on-migrate=true

#JJWT
jwt.secret=${JWT_SECRET:cambiar-este-valor-en-produccion-por-uno-largo-y-random}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

app.admin.correo=${ADMIN_EMAIL:admin@modalink.com}
app.admin.password=${ADMIN_PASSWORD:admin123}
app.admin.dni=${ADMIN_DNI:00000000}

# Por si tengo problemas... descomentar
#logging.level.org.springframework.security=DEBUG