--
-- ER/Studio Data Architect SQL Code Generation

-- Date Created : Saturday, September 26, 2026 21:01:14
-- Target DBMS : PostgreSQL 8.0
--

-- 
-- TABLE: actividad 
--

CREATE TABLE actividad(
    id_actividad         int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    estado               varchar(50)     NOT NULL,
    nombre               varchar(20)     NOT NULL,
    duracion_minutos     int4            NOT NULL,
    fecha_hora_inicio    timestamp       NOT NULL,
    descripcion          varchar(200),
    id_planificacion     int8            NOT NULL,
    id_ubicacion         int8            NOT NULL,
    CONSTRAINT chk_actividad_duracion CHECK (duracion_minutos > 0),
    CONSTRAINT chk_estado_actividad CHECK (estado IN ('PENDIENTE', 'EN_CURSO', 'FINALIZADA', 'CANCELADA')),
    CONSTRAINT "PK_actividad" PRIMARY KEY (id_actividad)
)
;
-- Derivacion automatica de cumplimiento de hitos y notificacion a los Directores
CREATE OR REPLACE FUNCTION fn_derivar_cumplimiento_hito() RETURNS trigger AS $$
DECLARE
    r_hito RECORD;
    r_director RECORD;
    v_pendientes INT;
    v_id_rol_director BIGINT;
BEGIN
    -- Se dispara cuando la actividad pasa a 'FINALIZADA'
    IF NEW.estado = 'FINALIZADA' AND (OLD.estado IS NULL OR OLD.estado <> 'FINALIZADA') THEN
        
        SELECT id_rol_proyecto INTO v_id_rol_director
        FROM rol_proyecto
        WHERE codigo = 'DIRECTOR';

        FOR r_hito IN
            SELECT h.id_hito, h.id_proyecto, h.nombre AS nombre_hito
            FROM hito h
            JOIN hito_actividad ha ON h.id_hito = ha.id_hito
            WHERE ha.id_actividad = NEW.id_actividad
              AND h.estado <> 'CUMPLIDO'
        LOOP
            -- Verificar si quedan actividades sin finalizar para este hito
            SELECT COUNT(*) INTO v_pendientes
            FROM hito_actividad ha_sub
            JOIN actividad a ON ha_sub.id_actividad = a.id_actividad
            WHERE ha_sub.id_hito = r_hito.id_hito
              AND a.estado <> 'FINALIZADA';

            -- Si no quedan pendientes, el hito se marca como cumplido automaticamente
            IF v_pendientes = 0 THEN
                UPDATE hito
                SET estado = 'CUMPLIDO',
                    fecha_cumplimiento = clock_timestamp()
                WHERE id_hito = r_hito.id_hito;

                -- Notificar a todos los directores activos del proyecto
                IF v_id_rol_director IS NOT NULL THEN
                    FOR r_director IN
                        SELECT per.id_usuario
                        FROM miembros_proyecto mp
                        JOIN perfil per ON mp.id_perfil = per.id_perfil
                        WHERE mp.id_proyecto = r_hito.id_proyecto
                          AND mp.estado_participacion = 'ACTIVO'
                          AND mp.id_rol_proyecto = v_id_rol_director
                    LOOP
                        INSERT INTO notificacion (
                            id_usuario_destino,
                            tipo,
                            mensaje,
                            entidad_tipo,
                            entidad_id,
                            leida,
                            fecha_generada
                        ) VALUES (
                            r_director.id_usuario,
                            'HitoCumplido',
                            'El hito "' || r_hito.nombre_hito || '" ha sido completado.',
                            'hito',
                            r_hito.id_hito,
                            false,
                            clock_timestamp()
                        );
                    END LOOP;
                END IF;
            END IF;
        END LOOP;
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_derivar_cumplimiento_hito ON actividad;
CREATE TRIGGER trg_derivar_cumplimiento_hito
    AFTER UPDATE OF estado ON actividad
    FOR EACH ROW EXECUTE FUNCTION fn_derivar_cumplimiento_hito();

-- 
-- TABLE: agenda 
--

CREATE TABLE agenda(
    id_agenda               int8     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    margen_actividad_min    int4    DEFAULT 30 NOT NULL,
    id_usuario              int8    NOT NULL,
    CONSTRAINT chk_margen_positivo CHECK (margen_actividad_min >= 0),
    CONSTRAINT "PK_agenda" PRIMARY KEY (id_agenda)
)
;



-- 
-- TABLE: asignacion_actividad 
--

CREATE TABLE asignacion_actividad(
    id_asignacion_act    int8     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_miembro           int8    NOT NULL,
    id_actividad         int8    NOT NULL,
    CONSTRAINT "PK_asignacion_actividad" PRIMARY KEY (id_asignacion_act)
)
;
-- Notificacion de asignacion
CREATE OR REPLACE FUNCTION fn_notificar_asignacion_actividad() RETURNS trigger AS $$
DECLARE
    v_id_usuario_destino BIGINT;
    v_nombre_actividad VARCHAR(100);
    v_nombre_proyecto VARCHAR(100);
BEGIN
    -- Obtener el id_usuario asociado al perfil del miembro
    SELECT p.id_usuario INTO v_id_usuario_destino
    FROM miembros_proyecto mp
    JOIN perfil p ON p.id_perfil = mp.id_perfil
    WHERE mp.id_miembro = NEW.id_miembro;

    -- Obtener nombre de la actividad y del proyecto
    SELECT a.nombre, proy.nombre
    INTO v_nombre_actividad, v_nombre_proyecto
    FROM actividad a
    JOIN planificacion pl ON pl.id_planificacion = a.id_planificacion
    JOIN proyecto proy ON proy.id_proyecto = pl.id_proyecto
    WHERE a.id_actividad = NEW.id_actividad;

    IF v_id_usuario_destino IS NOT NULL THEN
        INSERT INTO notificacion (
            id_usuario_destino,
            tipo,
            mensaje,
            entidad_tipo,
            entidad_id,
            leida,
            fecha_generada
        ) VALUES (
            v_id_usuario_destino,
            'AsignacionActividad',
            'Has sido asignado a la actividad "' || COALESCE(v_nombre_actividad, 'Sin Nombre') || '" en el proyecto "' || COALESCE(v_nombre_proyecto, 'Sin Nombre') || '".',
            'actividad',
            NEW.id_actividad,
            false,
            clock_timestamp()
        );
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_notificar_asignacion_actividad ON asignacion_actividad;
CREATE TRIGGER trg_notificar_asignacion_actividad
    AFTER INSERT ON asignacion_actividad
    FOR EACH ROW EXECUTE FUNCTION fn_notificar_asignacion_actividad();

-- 
-- TABLE: auditoria 
--

CREATE TABLE auditoria(
    id_auditoria         int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_bd           varchar(200)    DEFAULT CURRENT_USER NOT NULL,
    entidad_afectada     varchar(100)    NOT NULL,
    id_afectado          int8            NOT NULL,
    fecha_hora           timestamp       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ip_usuario           varchar(45),
    id_tipo_auditoria    int8            NOT NULL,
    id_usuario           int8,
    CONSTRAINT "PK_auditoria" PRIMARY KEY (id_auditoria)
)
;



-- 
-- TABLE: bloqueo_agenda 
--

CREATE TABLE bloqueo_agenda(
    id_bloqueo           int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_hora_inicio    timestamp       NOT NULL,
    fecha_hora_fin       timestamp       NOT NULL,
    motivo               varchar(200)    NOT NULL,
    id_agenda            int8            NOT NULL,
    CONSTRAINT chk_bloqueo_rango CHECK (fecha_hora_fin > fecha_hora_inicio),
    CONSTRAINT "PK_bloqueo_agenda" PRIMARY KEY (id_bloqueo)
)
;
--Impedir solapamiento entre bloqueos manuales de la misma agenda
CREATE OR REPLACE FUNCTION fn_validar_solape_bloqueo() RETURNS trigger AS $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM bloqueo_agenda b
        WHERE b.id_agenda = NEW.id_agenda
          AND b.id_bloqueo IS DISTINCT FROM NEW.id_bloqueo
          AND NEW.fecha_hora_inicio < b.fecha_hora_fin
          AND NEW.fecha_hora_fin > b.fecha_hora_inicio
    ) THEN
        RAISE EXCEPTION 'El bloqueo se superpone con otro bloqueo existente de la agenda.';
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_bloqueo_no_solape ON bloqueo_agenda;
CREATE TRIGGER trg_bloqueo_no_solape
    BEFORE INSERT OR UPDATE ON bloqueo_agenda
    FOR EACH ROW EXECUTE FUNCTION fn_validar_solape_bloqueo();
    
-- Impedir liberar un bloqueo cubierto por una actividad confirmada/publicada
-- Adaptado a: margen_actividad_min, calculo de fin por duracion_minutos y estados en mayusculas
CREATE OR REPLACE FUNCTION fn_validar_bloqueo_no_actividad() RETURNS trigger AS $$
DECLARE
    v_margen INT;
    v_id_usuario BIGINT;
BEGIN
    SELECT margen_actividad_min INTO v_margen
    FROM agenda WHERE id_agenda = OLD.id_agenda;

    v_margen := COALESCE(v_margen, 30);

    SELECT a.id_usuario INTO v_id_usuario
    FROM agenda a WHERE a.id_agenda = OLD.id_agenda;

    IF EXISTS (
        SELECT 1
        FROM asignacion_actividad aa
        JOIN actividad act ON act.id_actividad = aa.id_actividad
        JOIN planificacion pl ON pl.id_planificacion = act.id_planificacion
        JOIN proyecto p ON p.id_proyecto = pl.id_proyecto
        JOIN miembros_proyecto mp ON mp.id_miembro = aa.id_miembro
        JOIN perfil pf ON pf.id_perfil = mp.id_perfil
        WHERE p.estado IN ('PUBLICADO', 'CONFIRMADO')
          AND mp.estado_participacion = 'ACTIVO'
          AND pf.id_usuario = v_id_usuario
          -- Fin de actividad calculado a partir de fecha_hora_inicio + duracion_minutos
          AND OLD.fecha_hora_inicio < (act.fecha_hora_inicio + (act.duracion_minutos * INTERVAL '1 minute') + (v_margen * INTERVAL '1 minute'))
          AND OLD.fecha_hora_fin > (act.fecha_hora_inicio - (v_margen * INTERVAL '1 minute'))
    ) THEN
        RAISE EXCEPTION 'No se puede liberar un horario comprometido por una actividad de proyecto.';
    END IF;
    RETURN OLD;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_bloqueo_no_liberar_actividad ON bloqueo_agenda;
CREATE TRIGGER trg_bloqueo_no_liberar_actividad
    BEFORE DELETE ON bloqueo_agenda
    FOR EACH ROW EXECUTE FUNCTION fn_validar_bloqueo_no_actividad();

-- 
-- TABLE: caracteristica_perfil 
--

CREATE TABLE caracteristica_perfil(
    id_caracteristica_perfil    int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor                       varchar(50),
    fecha_registro              timestamp      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_perfil                   int8           NOT NULL,
    id_valor                    int8,
    id_caracteristica           int8           NOT NULL,
    CONSTRAINT "PK_caracteristica_perfil" PRIMARY KEY (id_caracteristica_perfil)
)
;
-- Validar que la caracteristica tecnica pertenezca a la profesion del perfil
CREATE OR REPLACE FUNCTION chk_caracteristica_tecnica_de_profesion() RETURNS trigger AS $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM caracteristica_tecnica ct
        JOIN perfil p ON p.id_perfil = NEW.id_perfil
        WHERE ct.id_caracteristica = NEW.id_caracteristica
          AND ct.id_profesion = p.id_profesion
    ) THEN
        RAISE EXCEPTION 'La caracteristica tecnica seleccionada no corresponde a la profesion del perfil.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_caracteristica_tecnica_de_profesion ON caracteristica_perfil;
CREATE TRIGGER trg_caracteristica_tecnica_de_profesion
    BEFORE INSERT OR UPDATE OF id_caracteristica, id_perfil ON caracteristica_perfil
    FOR EACH ROW EXECUTE FUNCTION chk_caracteristica_tecnica_de_profesion();

-- Consistencia: valor XOR id_valor segun el tipo_dato de la caracteristica tecnica
CREATE OR REPLACE FUNCTION chk_caracteristica_perfil_valor() RETURNS trigger AS $$
DECLARE
    v_tipo_dato VARCHAR(50);
BEGIN
    SELECT tipo_dato INTO v_tipo_dato
    FROM caracteristica_tecnica
    WHERE id_caracteristica = NEW.id_caracteristica;

    IF v_tipo_dato = 'ENUMERADO' THEN
        IF NEW.id_valor IS NULL OR NEW.valor IS NOT NULL THEN
            RAISE EXCEPTION 'Para caracteristicas de tipo ENUMERADO debe especificarse id_valor y el campo valor debe ser nulo.';
        END IF;
        IF NOT EXISTS (
            SELECT 1 FROM valor_caracteristica vc
            WHERE vc.id_valor = NEW.id_valor
              AND vc.id_caracteristica = NEW.id_caracteristica
        ) THEN
            RAISE EXCEPTION 'El id_valor no pertenece a la caracteristica tecnica indicada.';
        END IF;
    ELSE -- 'TEXTO' o 'NUMERICO'
        IF NEW.valor IS NULL OR NEW.id_valor IS NOT NULL THEN
            RAISE EXCEPTION 'Para caracteristicas de tipo TEXTO o NUMERICO debe especificarse valor y id_valor debe ser nulo.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_caracteristica_perfil_valor ON caracteristica_perfil;
CREATE TRIGGER trg_caracteristica_perfil_valor
    BEFORE INSERT OR UPDATE OF valor, id_valor, id_caracteristica ON caracteristica_perfil
    FOR EACH ROW EXECUTE FUNCTION chk_caracteristica_perfil_valor();
    
-- valor NO negativo para caracteristicas numericas ingresadas por teclado 
CREATE OR REPLACE FUNCTION chk_caracteristica_valor_no_negativo() RETURNS trigger AS $$
DECLARE
    v_tipo_dato VARCHAR(50);
    v_numero    DOUBLE PRECISION;
BEGIN
    SELECT tipo_dato INTO v_tipo_dato
    FROM caracteristica_tecnica
    WHERE id_caracteristica = NEW.id_caracteristica;

    IF v_tipo_dato = 'NUMERICO' THEN
        IF NEW.valor IS NULL THEN
            RAISE EXCEPTION 'Para caracteristicas tecnicas de tipo NUMERICO debe proveerse un valor numerico.';
        END IF;
        BEGIN
            v_numero := NEW.valor::double precision;
        EXCEPTION WHEN invalid_text_representation THEN
            RAISE EXCEPTION 'El valor "%" no es un numero valido para la caracteristica tecnica.', NEW.valor;
        END;

        IF v_numero < 0 THEN
            RAISE EXCEPTION 'La caracteristica tecnica numerica no admite valores negativos.';
        END IF;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_caracteristica_valor_no_negativo ON caracteristica_perfil;
CREATE TRIGGER trg_caracteristica_valor_no_negativo
    BEFORE INSERT OR UPDATE OF valor, id_caracteristica ON caracteristica_perfil
    FOR EACH ROW EXECUTE FUNCTION chk_caracteristica_valor_no_negativo();

-- 
-- TABLE: caracteristica_tecnica 
--

CREATE TABLE caracteristica_tecnica(
    id_caracteristica    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_dato            varchar(50)     NOT NULL,
    codigo               varchar(50)     NOT NULL,
    nombre               varchar(100),
    id_profesion         int8            NOT NULL,
    id_unidad            int8,
    CONSTRAINT chk_codigo_mayus CHECK (codigo = UPPER(codigo)),
    CONSTRAINT chk_caracteristica_tecnica_tipo_dato CHECK (tipo_dato IN ('ENUMERADO', 'TEXTO', 'NUMERICO')),
    CONSTRAINT "PK_caracteristica_tecnica" PRIMARY KEY (id_caracteristica)
)
;


-- 
-- TABLE: ciudad 
--

CREATE TABLE ciudad(
    id_ciudad           int8               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre              varchar(100)      NOT NULL,
    codigo_postal       varchar(10),
    id_externo          varchar(50)       NOT NULL,
    fuente_api          varchar(50)       NOT NULL,
    activo              boolean           DEFAULT true NOT NULL,
    longitud_defecto    decimal(11, 8),
    latitud_defecto     decimal(10, 8),
    id_provincia        int8              NOT NULL,
    CONSTRAINT "PK_ciudad" PRIMARY KEY (id_ciudad)
)
;



-- 
-- TABLE: colaborador_publicacion 
--

CREATE TABLE colaborador_publicacion(
    id_publicacion    int8    NOT NULL,
    id_perfil         int8    NOT NULL,
    CONSTRAINT "PK_colaborador_publicacion" PRIMARY KEY (id_publicacion, id_perfil)
)
;



-- 
-- TABLE: comentario 
--

CREATE TABLE comentario(
    id_comentario       int8              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    texto               varchar(1000),
    fecha_comentario    timestamp        NOT NULL,
    id_publicacion      int8             NOT NULL,
    id_perfil           int8             NOT NULL,
    CONSTRAINT chk_texto_vacio CHECK (char_length(trim(texto)) > 0),
    CONSTRAINT "PK_comentario" PRIMARY KEY (id_comentario)
)
;



-- 
-- TABLE: configuracion_sistema 
--

CREATE TABLE configuracion_sistema(
    clave          varchar(100)    NOT NULL,
    valor          varchar(255)    NOT NULL,
    descripcion    varchar(255),
    CONSTRAINT "PK_clave_config" PRIMARY KEY (clave)
)
;


-- 
-- TABLE: dependencia_actividades 
--

CREATE TABLE dependencia_actividades(
    id_actividad_sucesora       int8    NOT NULL,
    id_actividad_predecesora    int8    NOT NULL,
    CONSTRAINT chk_dependencia_no_autoreferencia CHECK (id_actividad_predecesora <> id_actividad_sucesora),
    CONSTRAINT "PK_dependencia_actividades" PRIMARY KEY (id_actividad_sucesora, id_actividad_predecesora)
)
;

-- Índice para acelerar la búsqueda por predecesora (usado por el trigger anti-ciclos)
CREATE INDEX idx_dependencia_predecesora
    ON dependencia_actividades (id_actividad_predecesora);

-- Trigger para evitar ciclos en la dependencia de actividades
CREATE OR REPLACE FUNCTION fn_dependencia_sin_ciclos()
RETURNS trigger AS $$
BEGIN
    -- Serializa inserciones concurrentes para evitar que dos transacciones
    -- creen A->B y B->A a la vez sin verse entre sí.
    PERFORM pg_advisory_xact_lock(hashtext('dependencia_actividades'));

    -- Arista nueva: predecesora -> sucesora.
    -- Se crea un ciclo si desde la sucesora ya se puede llegar a la predecesora.
    IF EXISTS (
        WITH RECURSIVE descendientes AS (
            SELECT d.id_actividad_sucesora AS id
            FROM dependencia_actividades d
            WHERE d.id_actividad_predecesora = NEW.id_actividad_sucesora
              AND NOT (TG_OP = 'UPDATE'
                       AND d.id_actividad_sucesora    = OLD.id_actividad_sucesora
                       AND d.id_actividad_predecesora = OLD.id_actividad_predecesora)
            UNION
            SELECT d.id_actividad_sucesora
            FROM dependencia_actividades d
            JOIN descendientes x ON d.id_actividad_predecesora = x.id
            WHERE NOT (TG_OP = 'UPDATE'
                       AND d.id_actividad_sucesora    = OLD.id_actividad_sucesora
                       AND d.id_actividad_predecesora = OLD.id_actividad_predecesora)
        )
        SELECT 1 FROM descendientes
        WHERE id = NEW.id_actividad_predecesora
    ) THEN
        RAISE EXCEPTION
            'Dependencia inválida: la actividad % como predecesora de % genera un ciclo',
            NEW.id_actividad_predecesora, NEW.id_actividad_sucesora
            USING ERRCODE = 'check_violation';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_dependencia_sin_ciclos
BEFORE INSERT OR UPDATE ON dependencia_actividades
FOR EACH ROW
EXECUTE FUNCTION fn_dependencia_sin_ciclos();


-- 
-- TABLE: detalle_auditoria 
--

CREATE TABLE detalle_auditoria(
    id_detalle_auditoria    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    campo                   varchar(100),
    valor_anterior          varchar(255)    NOT NULL,
    valor_nuevo             varchar(255)    NOT NULL,
    id_auditoria            int8            NOT NULL,
    CONSTRAINT "PK_detalle_auditoria" PRIMARY KEY (id_detalle_auditoria)
)
;



-- 
-- TABLE: genero 
--

CREATE TABLE genero(
    id_genero    int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo       varchar(50)    NOT NULL,
    nombre       varchar(50)    NOT NULL,
    CONSTRAINT "PK_genero" PRIMARY KEY (id_genero)
)
;


-- 
-- TABLE: habilidad 
--

CREATE TABLE habilidad(
    id_habilidad    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre          varchar(255)    NOT NULL,
    codigo          varchar(50)     NOT NULL,
    descripcion     varchar(255),
    CONSTRAINT "PK_habilidad" PRIMARY KEY (id_habilidad)
)
;


-- 
-- TABLE: habilidad_perfil 
--

CREATE TABLE habilidad_perfil(
    id_habilidad    int8    NOT NULL,
    id_perfil       int8    NOT NULL,
    CONSTRAINT "PK_habilidad_perfil" PRIMARY KEY (id_habilidad, id_perfil)
)
;



-- 
-- TABLE: hito 
--

CREATE TABLE hito(
    id_hito               int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_creacion        timestamp       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    nombre                varchar(100)    NOT NULL,
    descripcion           varchar(200)    NOT NULL,
    fecha_limite          timestamp,
    fecha_cumplimiento    timestamp,
    estado                varchar(50)     NOT NULL,
    id_proyecto           int8            NOT NULL,
    CONSTRAINT chk_hito_estado CHECK (estado IN ('PENDIENTE', 'CUMPLIDO', 'RETRASADO')),
    CONSTRAINT "PK_hito" PRIMARY KEY (id_hito)
)
;
-- Validar que la fecha límite del hito no supere la fecha de entrega de la planificación
CREATE OR REPLACE FUNCTION fn_validar_fecha_limite_hito() RETURNS trigger AS $$
DECLARE
    v_fecha_entrega DATE;
BEGIN
    IF NEW.fecha_limite IS NOT NULL THEN
        SELECT p.fecha_entrega INTO v_fecha_entrega
        FROM planificacion p
        WHERE p.id_proyecto = NEW.id_proyecto;

        IF v_fecha_entrega IS NOT NULL AND NEW.fecha_limite::DATE > v_fecha_entrega THEN
            RAISE EXCEPTION 'La fecha límite del hito (%) no puede superar la fecha de entrega de la planificación del proyecto (%).',
                NEW.fecha_limite::DATE, v_fecha_entrega;
        END IF;
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_fecha_limite_hito ON hito;
CREATE TRIGGER trg_validar_fecha_limite_hito
    BEFORE INSERT OR UPDATE OF fecha_limite, id_proyecto ON hito
    FOR EACH ROW EXECUTE FUNCTION fn_validar_fecha_limite_hito();

-- Impedir eliminar un hito con actividades asociadas
CREATE OR REPLACE FUNCTION fn_validar_borrado_hito() RETURNS trigger AS $$
DECLARE
    v_actividades_asociadas INT;
BEGIN
    SELECT COUNT(*) INTO v_actividades_asociadas
    FROM hito_actividad
    WHERE id_hito = OLD.id_hito;

    IF v_actividades_asociadas > 0 THEN
        RAISE EXCEPTION 'No se puede eliminar el hito (ID %) porque tiene % actividad(es) asociada(s). Debe desvincularlas primero.',
            OLD.id_hito, v_actividades_asociadas;
    END IF;

    RETURN OLD;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_borrado_hito ON hito;
CREATE TRIGGER trg_validar_borrado_hito
    BEFORE DELETE ON hito
    FOR EACH ROW EXECUTE FUNCTION fn_validar_borrado_hito();

-- 
-- TABLE: hito_actividad 
--

CREATE TABLE hito_actividad(
    id_hito         int8    NOT NULL,
    id_actividad    int8    NOT NULL,
    CONSTRAINT "PK_hito_actividad" PRIMARY KEY (id_hito, id_actividad)
)
;



-- 
-- TABLE: imagen 
--

CREATE TABLE imagen(
    id_imagen         int8              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url               varchar(1024)    NOT NULL,
    estado            varchar(50),
    nombre_archivo    varchar(255)     NOT NULL,
    tipo_imagen       varchar(255)     NOT NULL,
    tamano_bytes      int4             NOT NULL,
    fecha_subida      timestamp        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_imagen" PRIMARY KEY (id_imagen)
)
;



-- 
-- TABLE: imagen_moodboard 
--

CREATE TABLE imagen_moodboard(
    id_imagen       int8    NOT NULL,
    id_moodboard    int8    NOT NULL,
    CONSTRAINT "PK_imagen_moodboard" PRIMARY KEY (id_imagen, id_moodboard)
)
;



-- 
-- TABLE: imagen_publicacion 
--

CREATE TABLE imagen_publicacion(
    id_imagen         int8    NOT NULL,
    id_publicacion    int8    NOT NULL,
    CONSTRAINT "PK_imagen_publicacion" PRIMARY KEY (id_imagen, id_publicacion)
)
;



-- 
-- TABLE: invitacion_actividad 
--

CREATE TABLE invitacion_actividad(
    id_invitacion             int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mensaje                   varchar(255),
    fecha_envio               timestamp       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado                    varchar(50)     NOT NULL,
    id_perfil_remitente       int8            NOT NULL,
    id_requerimiento_act      int8            NOT NULL,
    id_perfil_destinatario    int8            NOT NULL,
    CONSTRAINT chk_invitacion_act_no_autoinvitacion CHECK (id_perfil_remitente <> id_perfil_destinatario),
    CONSTRAINT chk_invitacion_act_estado CHECK (estado IN ('PENDIENTE', 'RECHAZADA', 'ACEPTADA')),
    CONSTRAINT "PK_invitacion_actividad" PRIMARY KEY (id_invitacion)
)
;



-- 
-- TABLE: invitacion_gral 
--

CREATE TABLE invitacion_gral(
    id_invitacion_gral        int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    mensaje                   varchar(50),
    fecha_envio               timestamp      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado                    varchar(50)    NOT NULL,
    id_perfil_destinatario    int8           NOT NULL,
    id_perfil_remitente       int8           NOT NULL,
    id_requerimiento_gral     int8,
    CONSTRAINT chk_invitacion_gral_no_autoinvitacion CHECK (id_perfil_remitente <> id_perfil_destinatario),
    CONSTRAINT chk_invitacion_gral_estado CHECK (estado IN ('PENDIENTE', 'RECHAZADA', 'ACEPTADA')),
    CONSTRAINT "PK_invitacion_gral" PRIMARY KEY (id_invitacion_gral)
)
;



-- 
-- TABLE: jornada_agenda 
--

CREATE TABLE jornada_agenda(
    id_jornada            int8     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    dia_semana            int4    NOT NULL,
    hora_inicio_manana    time    NOT NULL,
    hora_fin_manana       time,
    hora_inicio_tarde     time,
    hora_fin_tarde        time    NOT NULL,
    id_agenda             int8    NOT NULL,
    CONSTRAINT chk_jornada_mediodia_completo CHECK ((hora_fin_manana IS NULL AND hora_inicio_tarde IS NULL) OR (hora_fin_manana IS NOT NULL AND hora_inicio_tarde IS NOT NULL)),
    CONSTRAINT chk_jornada_orden_bloques CHECK (hora_inicio_tarde IS NULL OR hora_inicio_tarde > hora_fin_manana),
    CONSTRAINT chk_jornada_rango_maniana CHECK (hora_fin_manana IS NULL OR hora_fin_manana > hora_inicio_manana),
    CONSTRAINT chk_jornada_rango_tarde CHECK (hora_inicio_tarde IS NULL OR hora_fin_tarde > hora_inicio_tarde),
    CONSTRAINT chk_jornada_rango_total CHECK (hora_fin_tarde > hora_inicio_manana),
    CONSTRAINT chk_jornada_dia_semana CHECK (dia_semana BETWEEN 1 AND 7),
    CONSTRAINT "PK_jornada_laboral" PRIMARY KEY (id_jornada)
)
;



-- 
-- TABLE: me_gusta 
--

CREATE TABLE me_gusta(
    id_publicacion    int8         NOT NULL,
    id_perfil         int8         NOT NULL,
    fecha             timestamp    DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT "PK_me_gusta_publicacion_perfil" PRIMARY KEY (id_publicacion, id_perfil)
)
;



-- 
-- TABLE: miembros_proyecto 
--

CREATE TABLE miembros_proyecto(
    id_miembro              int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "motivoBaja"            varchar(100),
    id_rol_proyecto         int8            NOT NULL,
    estado_participacion    varchar(50)     NOT NULL,
    id_proyecto             int8            NOT NULL,
    id_perfil               int8            NOT NULL,
    id_tyc_aceptado         int8            NOT NULL,
    CONSTRAINT chk_estado_participacion CHECK (estado_participacion IN ('ACTIVO', 'BAJA_VOLUNTARIA', 'ELIMINADO')),
    CONSTRAINT "PK_miembro_proyecto" PRIMARY KEY (id_miembro)
)
;
-- Validar que no se desactive o elimine al único director activo del proyecto
CREATE OR REPLACE FUNCTION fn_validar_minimo_un_director_miembro() RETURNS trigger AS $$
DECLARE
    v_id_rol_director BIGINT;
    v_id_proyecto BIGINT;
    v_cantidad_directores INT;
BEGIN
    SELECT id_rol_proyecto INTO v_id_rol_director
    FROM rol_proyecto
    WHERE codigo = 'DIRECTOR';

    IF v_id_rol_director IS NULL THEN
        -- Si no existe rol Director en la tabla, se permite la acción
        IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        IF OLD.id_rol_proyecto <> v_id_rol_director OR OLD.estado_participacion <> 'ACTIVO' THEN
            RETURN OLD;
        END IF;
        v_id_proyecto := OLD.id_proyecto;
    ELSE -- UPDATE
        IF OLD.id_rol_proyecto = v_id_rol_director AND OLD.estado_participacion = 'ACTIVO' THEN
            IF NEW.id_rol_proyecto = v_id_rol_director AND NEW.estado_participacion = 'ACTIVO' THEN
                RETURN NEW;
            END IF;
        ELSE
            RETURN NEW;
        END IF;
        v_id_proyecto := OLD.id_proyecto;
    END IF;

    SELECT COUNT(*) INTO v_cantidad_directores
    FROM miembros_proyecto
    WHERE id_proyecto = v_id_proyecto
      AND id_rol_proyecto = v_id_rol_director
      AND estado_participacion = 'ACTIVO'
      AND id_miembro <> OLD.id_miembro;

    IF v_cantidad_directores < 1 THEN
        RAISE EXCEPTION 'El proyecto (ID %) debe conservar al menos un director activo. No es posible remover o desactivar al unico director.', v_id_proyecto;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    ELSE
        RETURN NEW;
    END IF;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_minimo_un_director_miembro ON miembros_proyecto;
CREATE TRIGGER trg_validar_minimo_un_director_miembro
    BEFORE UPDATE OF id_rol_proyecto, estado_participacion OR DELETE ON miembros_proyecto
    FOR EACH ROW EXECUTE FUNCTION fn_validar_minimo_un_director_miembro();

-- 
-- TABLE: moodboard 
--

CREATE TABLE moodboard(
    id_moodboard      int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_creacion    timestamp       DEFAULT CURRENT_TIMESTAMP NOT NULL,
    descripcion       varchar(200),
    id_proyecto       int8            NOT NULL,
    CONSTRAINT "PK_moodboard" PRIMARY KEY (id_moodboard)
)
;



-- 
-- TABLE: notificacion 
--

CREATE TABLE notificacion(
    id_notificacion       int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo                  varchar(50),
    mensaje               text,
    entidad_tipo          varchar(50),
    entidad_id            int8,
    leida                 boolean        DEFAULT false NOT NULL,
    fecha_generada        timestamp      DEFAULT CURRENT_TIMESTAMP,
    id_usuario_destino    int8           NOT NULL,
    CONSTRAINT "PK_notificacion" PRIMARY KEY (id_notificacion)
)
;



-- 
-- TABLE: objetivo 
--

CREATE TABLE objetivo(
    id_objetivo    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre         varchar(100),
    descripcion    varchar(500),
    id_proyecto    int8            NOT NULL,
    CONSTRAINT "PK_objetivo" PRIMARY KEY (id_objetivo)
)
;



-- 
-- TABLE: pais 
--

CREATE TABLE pais(
    id_pais       int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo_iso    varchar(2)      NOT NULL,
    nombre        varchar(100)    NOT NULL,
    activo        boolean         DEFAULT true NOT NULL,
    CONSTRAINT "PK_pais" PRIMARY KEY (id_pais)
)
;


-- 
-- TABLE: perfil 
--

CREATE TABLE perfil(
    id_perfil               int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_usuario              int8            NOT NULL,
    fecha_solicitud_baja    timestamp,
    estado                  varchar(50)     NOT NULL,
    nombre_artistico        varchar(50)     NOT NULL,
    biografia               varchar(200)    NOT NULL,
    id_profesion            int8            NOT NULL,
    foto_perfil             int8,
    CONSTRAINT chk_perfil_nombre_artistico_len CHECK (char_length(trim(nombre_artistico)) >= 2),
    CONSTRAINT chk_perfil_biografia_len CHECK (char_length(trim(biografia)) >= 2),
    CONSTRAINT chk_perfil_estado CHECK (estado IN ('ACTIVO', 'DESHABILITADO', 'PENDIENTE_BAJA', 'BAJA')),
    CONSTRAINT "PK_perfil" PRIMARY KEY (id_perfil)
)
;
-- Unicidad de perfil activo/pendiente de baja por profesion y usuario
CREATE OR REPLACE FUNCTION chk_perfil_unico_por_profesion() RETURNS trigger AS $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM perfil
        WHERE id_usuario = NEW.id_usuario
          AND id_profesion = NEW.id_profesion
          AND estado IN ('ACTIVO', 'PENDIENTE_BAJA')
          AND id_perfil IS DISTINCT FROM NEW.id_perfil
    ) THEN
        RAISE EXCEPTION 'El usuario ya posee un perfil activo o en trámite de baja para la profesión indicada.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_perfil_unico_por_profesion ON perfil;
CREATE TRIGGER trg_perfil_unico_por_profesion
    BEFORE INSERT OR UPDATE OF id_usuario, id_profesion, estado ON perfil
    FOR EACH ROW EXECUTE FUNCTION chk_perfil_unico_por_profesion();
    
-- Prohibir modificar la profesion de un perfil existente
CREATE OR REPLACE FUNCTION chk_perfil_no_cambiar_profesion() RETURNS trigger AS $$
BEGIN
    IF NEW.id_profesion IS DISTINCT FROM OLD.id_profesion THEN
        RAISE EXCEPTION 'La profesión de un perfil no puede modificarse una vez creado.';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_perfil_no_cambiar_profesion ON perfil;
CREATE TRIGGER trg_perfil_no_cambiar_profesion
    BEFORE UPDATE OF id_profesion ON perfil
    FOR EACH ROW EXECUTE FUNCTION chk_perfil_no_cambiar_profesion();
    
-- Sincronizar fecha_solicitud_baja según el estado del perfil
CREATE OR REPLACE FUNCTION chk_perfil_fecha_solicitud_baja() RETURNS trigger AS $$
BEGIN
    IF NEW.estado = 'PENDIENTE_BAJA' AND (OLD.estado IS NULL OR OLD.estado <> 'PENDIENTE_BAJA') THEN
        IF NEW.fecha_solicitud_baja IS NULL THEN
            NEW.fecha_solicitud_baja := clock_timestamp();
        END IF;
    ELSIF NEW.estado = 'ACTIVO' THEN
        NEW.fecha_solicitud_baja := NULL;
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_perfil_fecha_solicitud_baja ON perfil;
CREATE TRIGGER trg_perfil_fecha_solicitud_baja
    BEFORE UPDATE OF estado ON perfil
    FOR EACH ROW EXECUTE FUNCTION chk_perfil_fecha_solicitud_baja();

-- 
-- TABLE: perfil_tyc 
--

CREATE TABLE perfil_tyc(
    id_perfil       int8            NOT NULL,
    id_tyc          int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion     varchar(200)    NOT NULL,
    fecha_inicio    timestamp       NOT NULL,
    fecha_fin       timestamp,
    CONSTRAINT ck_tyc_perfil_fecha_fin CHECK (fecha_fin IS NULL OR fecha_fin > fecha_inicio),
    CONSTRAINT "PK_perfil_tyc" PRIMARY KEY (id_perfil, id_tyc)
)
;



-- 
-- TABLE: permiso_global 
--

CREATE TABLE permiso_global(
    id_permiso_global    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre               varchar(255)    NOT NULL,
    CONSTRAINT "PK_permiso_global" PRIMARY KEY (id_permiso_global)
)
;


-- 
-- TABLE: permiso_proyecto 
--

CREATE TABLE permiso_proyecto(
    id_permiso_proyecto    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre                 varchar(255)    NOT NULL,
    CONSTRAINT "PK_permiso_proyecto" PRIMARY KEY (id_permiso_proyecto)
)
;


-- 
-- TABLE: planificacion 
--

CREATE TABLE planificacion(
    id_planificacion    int8     GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_entrega       date,
    id_proyecto         int8    NOT NULL,
    CONSTRAINT "PK_planificacion" PRIMARY KEY (id_planificacion)
)
;
-- Validacion coherencia de fechas entre planificacion y proyecto
CREATE OR REPLACE FUNCTION fn_validar_planificacion_fecha_coherente() RETURNS trigger AS $$
DECLARE
    v_fecha_inicio TIMESTAMP;
BEGIN
    IF NEW.fecha_entrega IS NOT NULL THEN
        SELECT p.fecha_inicio INTO v_fecha_inicio
        FROM proyecto p WHERE p.id_proyecto = NEW.id_proyecto;

        IF v_fecha_inicio IS NOT NULL AND NEW.fecha_entrega < v_fecha_inicio::DATE THEN
            RAISE EXCEPTION 'La fecha de entrega de la planificación (%) no puede ser anterior a la fecha de inicio del proyecto (%).',
                NEW.fecha_entrega, v_fecha_inicio::DATE;
        END IF;
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_validar_planificacion_fecha_coherente ON planificacion;
CREATE TRIGGER trg_validar_planificacion_fecha_coherente
    BEFORE INSERT OR UPDATE OF fecha_entrega, id_proyecto ON planificacion
    FOR EACH ROW EXECUTE FUNCTION fn_validar_planificacion_fecha_coherente();

-- 
-- TABLE: postulacion_actividad 
--

CREATE TABLE postulacion_actividad(
    id_postulacion          int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_postulacion       timestamp      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado                  varchar(50)    NOT NULL,
    id_perfil               int8           NOT NULL,
    id_requerimiento_act    int8           NOT NULL,
    CONSTRAINT chk_postulacion_act_estado CHECK (estado IN ('PENDIENTE', 'RECHAZADA', 'ACEPTADA')),
    CONSTRAINT "PK_postulacion_actividad" PRIMARY KEY (id_postulacion)
)
;
-- Control de postulaciones y cupos cada vez que se acepta una postulacion 
CREATE OR REPLACE FUNCTION fn_control_cupo_postulacion_actividad() RETURNS trigger AS $$
DECLARE
    v_cantidad_requerida INT;
    v_aceptadas_actuales INT;
BEGIN
    -- Se evalúa únicamente cuando la postulación pasa a 'ACEPTADA'
    IF NEW.estado = 'ACEPTADA' AND (OLD.estado IS NULL OR OLD.estado <> 'ACEPTADA') THEN
        
        -- Obtener la cantidad requerida para esta actividad
        SELECT ra.cantidad INTO v_cantidad_requerida
        FROM requerimiento_actividad ra
        WHERE ra.id_requerimiento_act = NEW.id_requerimiento_act;

        -- Contar cuántas postulaciones aceptadas existen en total (incluyendo la actual)
        SELECT COUNT(*) INTO v_aceptadas_actuales
        FROM postulacion_actividad
        WHERE id_requerimiento_act = NEW.id_requerimiento_act
          AND estado = 'ACEPTADA';

        -- Si se alcanzo o supero el cupo solicitado, cerrar las demas postulaciones pendientes
        IF v_cantidad_requerida IS NOT NULL AND v_aceptadas_actuales >= v_cantidad_requerida THEN
            UPDATE postulacion_actividad
            SET estado = 'RECHAZADA'
            WHERE id_requerimiento_act = NEW.id_requerimiento_act
              AND id_postulacion <> NEW.id_postulacion
              AND estado = 'PENDIENTE';
        END IF;
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_control_cupo_postulacion_actividad ON postulacion_actividad;
CREATE TRIGGER trg_control_cupo_postulacion_actividad
    AFTER UPDATE OF estado ON postulacion_actividad
    FOR EACH ROW EXECUTE FUNCTION fn_control_cupo_postulacion_actividad();

-- 
-- TABLE: postulacion_gral 
--

CREATE TABLE postulacion_gral(
    id_postulacion_gral      int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_postulacion        timestamp      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    estado                   varchar(50)    NOT NULL,
    id_perfil                int8           NOT NULL,
    id_requerimiento_gral    int8           NOT NULL,
    CONSTRAINT chk_postulacion_gral_estado CHECK (estado IN ('PENDIENTE', 'RECHAZADA', 'ACEPTADA')),
    CONSTRAINT "PK_postulacion_general" PRIMARY KEY (id_postulacion_gral)
)
;
-- Control de cupo para postulaciones generales
CREATE OR REPLACE FUNCTION fn_control_cupo_postulacion_gral() RETURNS trigger AS $$
DECLARE
    v_cantidad_requerida INT;
    v_aceptadas_actuales INT;
BEGIN
    -- Se evalua únicamente cuando la postulación pasa a 'ACEPTADA'
    IF NEW.estado = 'ACEPTADA' AND (OLD.estado IS NULL OR OLD.estado <> 'ACEPTADA') THEN
        
        -- Obtener la cantidad requerida para este requerimiento general del proyecto
        SELECT rgp.cantidad INTO v_cantidad_requerida
        FROM requerimiento_gral_proyecto rgp
        WHERE rgp.id_requerimiento_gral = NEW.id_requerimiento_gral;

        -- Contar cuántas postulaciones aceptadas existen en total (incluyendo la actual)
        SELECT COUNT(*) INTO v_aceptadas_actuales
        FROM postulacion_gral
        WHERE id_requerimiento_gral = NEW.id_requerimiento_gral
          AND estado = 'ACEPTADA';

        -- Si se alcanzo o supero el cupo solicitado, cerrar las demas postulaciones pendientes
        IF v_cantidad_requerida IS NOT NULL AND v_aceptadas_actuales >= v_cantidad_requerida THEN
            UPDATE postulacion_gral
            SET estado = 'RECHAZADA'
            WHERE id_requerimiento_gral = NEW.id_requerimiento_gral
              AND id_postulacion_gral <> NEW.id_postulacion_gral
              AND estado = 'PENDIENTE';
        END IF;
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_control_cupo_postulacion_gral ON postulacion_gral;
CREATE TRIGGER trg_control_cupo_postulacion_gral
    AFTER UPDATE OF estado ON postulacion_gral
    FOR EACH ROW EXECUTE FUNCTION fn_control_cupo_postulacion_gral();

-- 
-- TABLE: profesion 
--

CREATE TABLE profesion(
    id_profesion    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo          varchar(50)     NOT NULL,
    nombre          varchar(50)     NOT NULL,
    descripcion     varchar(200),
    CONSTRAINT "PK_profesion" PRIMARY KEY (id_profesion)
)
;


-- 
-- TABLE: provincia 
--

CREATE TABLE provincia(
    id_provincia    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre          varchar(100)    NOT NULL,
    id_externo      varchar(50)     NOT NULL,
    fuente_api      varchar(50)     NOT NULL,
    activo          boolean         DEFAULT true NOT NULL,
    id_pais         int8            NOT NULL,
    CONSTRAINT "PK_provincia" PRIMARY KEY (id_provincia)
)
;



-- 
-- TABLE: proyecto 
--

CREATE TABLE proyecto(
    id_proyecto                int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha_inicio               timestamp       NOT NULL,
    acepta_postulacion_gral    boolean         DEFAULT false NOT NULL,
    nombre                     varchar(50)     NOT NULL,
    descripcion                varchar(200)    NOT NULL,
    estado                     varchar(50)     NOT NULL,
    privacidad                 varchar(20)     NOT NULL,
    id_ubicacion               int8,
    CONSTRAINT chk_proyecto_estado CHECK (estado IN ('BORRADOR', 'PUBLICADO', 'CONFIRMADO', 'FINALIZADO', 'CANCELADO')),
    CONSTRAINT chk_proyecto_privacidad CHECK (privacidad IN ('PUBLICO', 'PRIVADO', 'OCULTO')),
    CONSTRAINT "PK_proyecto" PRIMARY KEY (id_proyecto)
)
;
-- Constraint trigger diferido. Asegura que el proyecto termine la transacción con al menos 1 director activo.
CREATE OR REPLACE FUNCTION fn_validar_proyecto_tiene_director() RETURNS trigger AS $$
DECLARE
    v_id_rol_director BIGINT;
    v_cantidad_directores INT;
BEGIN
    SELECT id_rol_proyecto INTO v_id_rol_director
    FROM rol_proyecto
    WHERE codigo = 'DIRECTOR';

    IF v_id_rol_director IS NOT NULL THEN
        SELECT COUNT(*) INTO v_cantidad_directores
        FROM miembros_proyecto
        WHERE id_proyecto = NEW.id_proyecto
          AND id_rol_proyecto = v_id_rol_director
          AND estado_participacion = 'ACTIVO';

        IF v_cantidad_directores < 1 THEN
            RAISE EXCEPTION 'El proyecto "%" (ID %) no cuenta con directores activos. Cada proyecto debe tener al menos uno.', NEW.nombre, NEW.id_proyecto;
        END IF;
    END IF;

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_proyecto_requiere_director ON proyecto;
CREATE CONSTRAINT TRIGGER trg_proyecto_requiere_director
    AFTER INSERT OR UPDATE ON proyecto
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION fn_validar_proyecto_tiene_director();
    
-- Auditoria sobre tabla proyecto    
    CREATE OR REPLACE FUNCTION fn_auditar_cambio_proyecto() RETURNS trigger AS $$
DECLARE
    v_id_tipo_auditoria BIGINT;
    v_id_auditoria BIGINT;
BEGIN
    -- Obtener id_tipo_auditoria según la acción (TG_OP en PostgreSQL es siempre 'INSERT', 'UPDATE' o 'DELETE' en mayúsculas)
    SELECT id_tipo_auditoria INTO v_id_tipo_auditoria
    FROM tipo_accion_auditoria 
    WHERE nombre = TG_OP;

    IF v_id_tipo_auditoria IS NULL THEN
        RAISE EXCEPTION 'No se encontró el tipo de acción de auditoría para la operación %', TG_OP;
    END IF;

    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND (OLD.estado <> NEW.estado OR OLD.privacidad <> NEW.privacidad)) THEN
        
        INSERT INTO auditoria (
            usuario_bd,
            entidad_afectada,
            id_afectado,
            fecha_hora,
            ip_usuario,
            id_tipo_auditoria,
            id_usuario
        ) VALUES (
            CURRENT_USER,
            'proyecto',
            COALESCE(NEW.id_proyecto, OLD.id_proyecto),
            clock_timestamp(),
            inet_client_addr()::varchar,
            v_id_tipo_auditoria,
            NULL 
        ) RETURNING id_auditoria INTO v_id_auditoria;

        IF TG_OP = 'UPDATE' AND OLD.estado <> NEW.estado THEN
            INSERT INTO detalle_auditoria (campo, valor_anterior, valor_nuevo, id_auditoria)
            VALUES ('estado', OLD.estado, NEW.estado, v_id_auditoria);
        END IF;

        IF TG_OP = 'UPDATE' AND OLD.privacidad <> NEW.privacidad THEN
            INSERT INTO detalle_auditoria (campo, valor_anterior, valor_nuevo, id_auditoria)
            VALUES ('privacidad', OLD.privacidad, NEW.privacidad, v_id_auditoria);
        END IF;

        IF TG_OP = 'DELETE' THEN
            INSERT INTO detalle_auditoria (campo, valor_anterior, valor_nuevo, id_auditoria)
            VALUES ('registro', OLD.nombre, 'ELIMINADO', v_id_auditoria);
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auditar_cambio_proyecto ON proyecto;
CREATE TRIGGER trg_auditar_cambio_proyecto
    AFTER UPDATE OF estado, privacidad OR DELETE ON proyecto
    FOR EACH ROW EXECUTE FUNCTION fn_auditar_cambio_proyecto();

-- 
-- TABLE: publicacion 
--

CREATE TABLE publicacion(
    id_publicacion       int8              GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo               varchar(150)     NOT NULL,
    descripcion          varchar(1000)    NOT NULL,
    fecha_publicacion    timestamp        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_perfil            int8             NOT NULL,
    id_proyecto          int8             NOT NULL,
    CONSTRAINT "PK_publicacion" PRIMARY KEY (id_publicacion)
)
;



-- 
-- TABLE: requerimiento_act_caract 
--

CREATE TABLE requerimiento_act_caract(
    id_req_act_caract       int8               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_requerimiento_act    int8              NOT NULL,
    id_caracteristica       int8              NOT NULL,
    valor_min               numeric(10, 2),
    valor_max               numeric(10, 2),
    CONSTRAINT "PK_requerimiento_act_caracteristica" PRIMARY KEY (id_req_act_caract)
)
;



-- 
-- TABLE: requerimiento_act_caract_valor 
--

CREATE TABLE requerimiento_act_caract_valor(
    id_req_act_caract    int8    NOT NULL,
    id_caracteristica    int8    NOT NULL,
    id_valor             int8    NOT NULL,
    CONSTRAINT "PK_requerimiento_act_caract_valor" PRIMARY KEY (id_req_act_caract, id_caracteristica, id_valor)
)
;



-- 
-- TABLE: requerimiento_act_habilidad 
--

CREATE TABLE requerimiento_act_habilidad(
    id_habilidad            int8    NOT NULL,
    id_requerimiento_act    int8    NOT NULL,
    CONSTRAINT "PK_requerimiento_act_habilidad" PRIMARY KEY (id_habilidad, id_requerimiento_act)
)
;



-- 
-- TABLE: requerimiento_actividad 
--

CREATE TABLE requerimiento_actividad(
    id_requerimiento_act    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cantidad                int4            NOT NULL,
    descripcion             varchar(200),
    id_profesion            int8            NOT NULL,
    id_actividad            int8            NOT NULL,
    CONSTRAINT chk_requerimiento_act_cantidad CHECK (cantidad > 0),
    CONSTRAINT "PK_requerimiento_actividad" PRIMARY KEY (id_requerimiento_act)
)
;



-- 
-- TABLE: requerimiento_gral_caract 
--

CREATE TABLE requerimiento_gral_caract(
    id_req_gral_caract       int8               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    valor_min                numeric(10, 2),
    valor_max                numeric(10, 2),
    id_requerimiento_gral    int8              NOT NULL,
    id_caracteristica        int8              NOT NULL,
    CONSTRAINT "PK_requerimiento_gral_caracteristica" PRIMARY KEY (id_req_gral_caract)
)
;



-- 
-- TABLE: requerimiento_gral_caract_valor 
--

CREATE TABLE requerimiento_gral_caract_valor(
    id_valor              int8    NOT NULL,
    id_caracteristica     int8    NOT NULL,
    id_req_gral_caract    int8    NOT NULL,
    CONSTRAINT "PK_requerimiento_gral_caract_valor" PRIMARY KEY (id_valor, id_caracteristica, id_req_gral_caract)
)
;



-- 
-- TABLE: requerimiento_gral_habilidad 
--

CREATE TABLE requerimiento_gral_habilidad(
    id_habilidad             int8    NOT NULL,
    id_requerimiento_gral    int8    NOT NULL,
    CONSTRAINT "PK_requerimiento_gral_actividad" PRIMARY KEY (id_habilidad, id_requerimiento_gral)
)
;



-- 
-- TABLE: requerimiento_gral_proyecto 
--

CREATE TABLE requerimiento_gral_proyecto(
    id_requerimiento_gral    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    cantidad                 int4            NOT NULL,
    descripcion              varchar(200),
    id_proyecto              int8            NOT NULL,
    id_profesion             int8            NOT NULL,
    CONSTRAINT chk_requerimiento_gral_cantidad CHECK (cantidad > 0),
    CONSTRAINT "PK_requerimiento_gral_proyecto" PRIMARY KEY (id_requerimiento_gral)
)
;



-- 
-- TABLE: rol_global 
--

CREATE TABLE rol_global(
    id_rol_global    int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre           varchar(50)    NOT NULL,
    codigo           varchar(50)    NOT NULL,
    CONSTRAINT "PK_rol_global" PRIMARY KEY (id_rol_global)
)
;


-- 
-- TABLE: rol_global_permiso 
--

CREATE TABLE rol_global_permiso(
    id_rol_global        int8    NOT NULL,
    id_permiso_global    int8    NOT NULL,
    CONSTRAINT "PK_rol_global_permiso" PRIMARY KEY (id_rol_global, id_permiso_global)
)
;


-- 
-- TABLE: rol_proyecto 
--

CREATE TABLE rol_proyecto(
    id_rol_proyecto    int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    codigo             varchar(50)    NOT NULL,
    nombre             varchar(50)    NOT NULL,
    CONSTRAINT "PK_rol_proyecto" PRIMARY KEY (id_rol_proyecto)
)
;


-- 
-- TABLE: rol_proyecto_permiso 
--

CREATE TABLE rol_proyecto_permiso(
    id_rol_proyecto        int8    NOT NULL,
    id_permiso_proyecto    int8    NOT NULL,
    CONSTRAINT "PK_rol_proyecto_permiso" PRIMARY KEY (id_rol_proyecto, id_permiso_proyecto)
)
;




-- 
-- TABLE: solicitud_colaboracion 
--

CREATE TABLE solicitud_colaboracion(
    id_solicitud_colaboracion    int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    estado                       varchar(50)    NOT NULL,
    fecha_envio                  timestamp      DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_publicacion               int8           NOT NULL,
    id_perfil_remitente          int8           NOT NULL,
    id_perfil_destinatario       int8           NOT NULL,
    CONSTRAINT "PK_solicitud_colaboracion" PRIMARY KEY (id_solicitud_colaboracion)
)
;



-- 
-- TABLE: tipo_accion_auditoria 
--

CREATE TABLE tipo_accion_auditoria(
    id_tipo_auditoria    int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre               varchar(100)    NOT NULL,
    CONSTRAINT "PK_tipo_auditoria" PRIMARY KEY (id_tipo_auditoria)
)
;


-- 
-- TABLE: ubicacion 
--

CREATE TABLE ubicacion(
    id_ubicacion     int8               GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    direccion        varchar(100),
    codigo_postal    varchar(10),
    latitud          decimal(10, 8),
    longitud         decimal(11, 8),
    id_ciudad        int8 NOT NULL,
    CONSTRAINT "PK_ubicacion" PRIMARY KEY (id_ubicacion)
)
;
-- Heredar las coordenadas de ciudad si no son especificadas 
CREATE OR REPLACE FUNCTION fn_heredar_coordenadas_ciudad() RETURNS trigger AS $$
BEGIN
    IF NEW.latitud IS NULL OR NEW.longitud IS NULL THEN
        SELECT c.latitud_defecto, c.longitud_defecto
        INTO NEW.latitud, NEW.longitud
        FROM ciudad c
        WHERE c.id_ciudad = NEW.id_ciudad;
    END IF;
    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_heredar_coordenadas_ciudad ON ubicacion;
CREATE TRIGGER trg_heredar_coordenadas_ciudad
    BEFORE INSERT OR UPDATE OF id_ciudad, latitud, longitud ON ubicacion
    FOR EACH ROW EXECUTE FUNCTION fn_heredar_coordenadas_ciudad();

-- 
-- TABLE: unidad_medida 
--

CREATE TABLE unidad_medida(
    id_unidad              int8            GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nombre                 varchar(50),
    simbolo                varchar(50),
    tipo_dato_permitido    varchar(50),
    CONSTRAINT "PK_unidad" PRIMARY KEY (id_unidad)
)
;


-- 
-- TABLE: usuario 
--

CREATE TABLE usuario(
    id_usuario                     int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    motivo_deshabilitacion         varchar(255),
    fecha_hasta_deshabilitacion    timestamp,
    id_externo                     varchar(255),
    proveedor_auth                 varchar(255)    NOT NULL,
    password_hash                  varchar(255),
    fecha_solicitud_baja           timestamp,
    estado                         varchar(50)     NOT NULL,
    nombre                         varchar(50)     NOT NULL,
    dni                            varchar(15)     NOT NULL,
    fecha_nacimiento               date            NOT NULL,
    apellido                       varchar(50)     NOT NULL,
    correo                         varchar(255)    NOT NULL,
    id_ubicacion                   int8,
    id_genero                      int8            NOT NULL,
    id_rol_global                  int8            NOT NULL,
    CONSTRAINT chk_usuario_estado CHECK (estado IN ('ACTIVO', 'DESHABILITADO', 'PENDIENTE_BAJA', 'BAJA')),
    CONSTRAINT chk_usuario_proveedor CHECK (proveedor_auth IN ('LOCAL', 'GOOGLE')),
    CONSTRAINT chk_usuario_nombre_len CHECK (char_length(trim(nombre)) >= 2),
    CONSTRAINT chk_usuario_apellido_len CHECK (char_length(trim(apellido)) >= 2),
    CONSTRAINT chk_usuario_correo CHECK (correo LIKE '%@%.%'),
    CONSTRAINT chk_usuario_edad_minima CHECK (fecha_nacimiento <= CURRENT_DATE - INTERVAL '18 years'),
    CONSTRAINT "PK_usuario" PRIMARY KEY (id_usuario)
)
;
-- Validacion de DNI no negativo ni Alfanumerico
CREATE OR REPLACE FUNCTION chk_usuario_dni_no_negativo() RETURNS trigger AS $$
DECLARE
    v_numero BIGINT;
BEGIN
    IF NEW.dni IS NULL THEN
        RAISE EXCEPTION 'El DNI no puede ser nulo.';
    END IF;

    IF NOT NEW.dni ~ '^[0-9]+$' THEN
        RAISE EXCEPTION 'El DNI debe contener únicamente dígitos numéricos.';
    END IF;

    BEGIN
        v_numero := NEW.dni::bigint;
    EXCEPTION WHEN invalid_text_representation OR numeric_value_out_of_range THEN
        RAISE EXCEPTION 'El DNI debe ser un número válido.';
    END;

    IF v_numero < 0 THEN
        RAISE EXCEPTION 'El DNI no puede ser un número negativo.';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_usuario_dni_no_negativo ON usuario;
CREATE TRIGGER trg_usuario_dni_no_negativo
    BEFORE INSERT OR UPDATE ON usuario
    FOR EACH ROW EXECUTE FUNCTION chk_usuario_dni_no_negativo();


-- Creacion automatica de agenda y jornadas laborales al registrar un usuario
-- Adaptado a columnas: margen_actividad_min, hora_inicio_manana, hora_fin_tarde

CREATE OR REPLACE FUNCTION fn_crear_agenda() RETURNS trigger AS $$
DECLARE
    v_id_agenda BIGINT;
BEGIN
    INSERT INTO agenda (margen_actividad_min, id_usuario)
    VALUES (30, NEW.id_usuario)
    RETURNING id_agenda INTO v_id_agenda;

    -- Lunes (1) a Viernes (5), jornada corrida estandar 09:00 a 18:00
    INSERT INTO jornada_agenda (id_agenda, dia_semana, hora_inicio_manana, hora_fin_tarde)
    SELECT v_id_agenda, d, '09:00'::TIME, '18:00'::TIME
    FROM (VALUES (1), (2), (3), (4), (5)) AS v(d);

    RETURN NEW;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_agenda_crear ON usuario;
CREATE TRIGGER trg_agenda_crear
    AFTER INSERT ON usuario
    FOR EACH ROW EXECUTE FUNCTION fn_crear_agenda();

-- Auditoria sobre tabla usuario (Cambios de estado, baja y datos sensibles)
CREATE OR REPLACE FUNCTION fn_auditar_cambio_usuario() RETURNS trigger AS $$
DECLARE
    v_id_tipo_auditoria BIGINT;
    v_id_auditoria BIGINT;
BEGIN
    -- Obtener id_tipo_auditoria según la acción (TG_OP en PostgreSQL es siempre 'INSERT', 'UPDATE' o 'DELETE' en mayúsculas)
    SELECT id_tipo_auditoria INTO v_id_tipo_auditoria
    FROM tipo_accion_auditoria 
    WHERE nombre = TG_OP;

    IF v_id_tipo_auditoria IS NULL THEN
        RAISE EXCEPTION 'No se encontró el tipo de acción de auditoría para la operación %', TG_OP;
    END IF;

    -- Si cambió el estado o se está eliminando el usuario
    IF TG_OP = 'DELETE' OR (TG_OP = 'UPDATE' AND (OLD.estado <> NEW.estado OR OLD.id_rol_global <> NEW.id_rol_global)) THEN
        
        INSERT INTO auditoria (
            usuario_bd,
            entidad_afectada,
            id_afectado,
            fecha_hora,
            ip_usuario,
            id_tipo_auditoria,
            id_usuario
        ) VALUES (
            CURRENT_USER,
            'usuario',
            COALESCE(NEW.id_usuario, OLD.id_usuario),
            clock_timestamp(),
            inet_client_addr()::varchar,
            v_id_tipo_auditoria,
            COALESCE(NEW.id_usuario, OLD.id_usuario)
        ) RETURNING id_auditoria INTO v_id_auditoria;

        -- Registrar detalle del cambio de estado si varió
        IF TG_OP = 'UPDATE' AND OLD.estado <> NEW.estado THEN
            INSERT INTO detalle_auditoria (campo, valor_anterior, valor_nuevo, id_auditoria)
            VALUES ('estado', OLD.estado, NEW.estado, v_id_auditoria);
        END IF;

        -- Registrar detalle del cambio de rol si varió
        IF TG_OP = 'UPDATE' AND OLD.id_rol_global <> NEW.id_rol_global THEN
            INSERT INTO detalle_auditoria (campo, valor_anterior, valor_nuevo, id_auditoria)
            VALUES ('id_rol_global', OLD.id_rol_global::varchar, NEW.id_rol_global::varchar, v_id_auditoria);
        END IF;

        -- Registrar detalle si fue borrado
        IF TG_OP = 'DELETE' THEN
            INSERT INTO detalle_auditoria (campo, valor_anterior, valor_nuevo, id_auditoria)
            VALUES ('registro', OLD.correo, 'ELIMINADO', v_id_auditoria);
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN RETURN OLD; ELSE RETURN NEW; END IF;
END $$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_auditar_cambio_usuario ON usuario;
CREATE TRIGGER trg_auditar_cambio_usuario
    AFTER UPDATE OF estado, id_rol_global OR DELETE ON usuario
    FOR EACH ROW EXECUTE FUNCTION fn_auditar_cambio_usuario();








-- 
-- TABLE: valor_caracteristica 
--

CREATE TABLE valor_caracteristica(
    id_valor             int8             GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    id_caracteristica    int8            NOT NULL,
    etiqueta             varchar(255),
    color_hex            varchar(7),
    CONSTRAINT chk_valor_caracteristica_color_hex CHECK (color_hex IS NULL OR color_hex ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT "PK_valor_caracteristica" PRIMARY KEY (id_valor, id_caracteristica)
)
;



-- 
-- INDEX: "UQ_asignacion_miembro_actividad" 
--

CREATE UNIQUE INDEX "UQ_asignacion_miembro_actividad" ON asignacion_actividad(id_miembro, id_actividad)
;
-- 
-- INDEX: "UQ_perfil_caracteristica" 
--

CREATE UNIQUE INDEX "UQ_perfil_caracteristica" ON caracteristica_perfil(id_perfil, id_caracteristica)
;

-- 
-- INDEX: "UQ_genero_codigo" 
--

CREATE UNIQUE INDEX "UQ_genero_codigo" ON genero(codigo)
;
-- 
-- INDEX: "UQ_genero_nombre" 
--

CREATE UNIQUE INDEX "UQ_genero_nombre" ON genero(nombre)
;
-- 
-- INDEX: "UQ_habilidad_codigo" 
--

CREATE UNIQUE INDEX "UQ_habilidad_codigo" ON habilidad(codigo)
;
-- 
-- INDEX: "UQ_habilidad_nombre" 
--

CREATE UNIQUE INDEX "UQ_habilidad_nombre" ON habilidad(nombre)
;
-- 
-- INDEX: "UQ_pais_nombre" 
--

CREATE UNIQUE INDEX "UQ_pais_nombre" ON pais(nombre)
;
-- 
-- INDEX: "UQ_pais_codigo_iso" 
--

CREATE UNIQUE INDEX "UQ_pais_codigo_iso" ON pais(codigo_iso)
;
-- 
-- INDEX: "UQ_permiso_global_nombre" 
--

CREATE UNIQUE INDEX "UQ_permiso_global_nombre" ON permiso_global(nombre)
;
-- 
-- INDEX: "UQ_permiso_proyecto_nombre" 
--

CREATE UNIQUE INDEX "UQ_permiso_proyecto_nombre" ON permiso_proyecto(nombre)
;
-- 
-- INDEX: "UQ_profesion_codigo" 
--

CREATE UNIQUE INDEX "UQ_profesion_codigo" ON profesion(codigo)
;
-- 
-- INDEX: "UQ_profesion_nombre" 
--

CREATE UNIQUE INDEX "UQ_profesion_nombre" ON profesion(nombre)
;
-- 
-- INDEX: "UQ_provincia_pais_nombre" 
--

CREATE UNIQUE INDEX "UQ_provincia_pais_nombre" ON provincia(nombre, id_pais)
;
-- 
-- INDEX: "UQ_rol_global_nombre" 
--

CREATE UNIQUE INDEX "UQ_rol_global_nombre" ON rol_global(nombre)
;
-- 
-- INDEX: "UQ_rol_global_codigo" 
--

CREATE UNIQUE INDEX "UQ_rol_global_codigo" ON rol_global(codigo)
;
-- 
-- INDEX: "UQ_rol_proyecto_nombre" 
--

CREATE UNIQUE INDEX "UQ_rol_proyecto_nombre" ON rol_proyecto(nombre)
;
-- 
-- INDEX: "UQ_tipo_accion_auditoria_nombre" 
--

CREATE UNIQUE INDEX "UQ_tipo_accion_auditoria_nombre" ON tipo_accion_auditoria(nombre)
;
-- 
-- INDEX: "UQ_unidad_medida_simbolo" 
--

CREATE UNIQUE INDEX "UQ_unidad_medida_simbolo" ON unidad_medida(simbolo)
;
-- 
-- INDEX: "UQ_usuario_correo" 
--

CREATE UNIQUE INDEX "UQ_usuario_correo" ON usuario(correo)
;
-- 
-- INDEX: "UQ_usuario_dni" 
--

CREATE UNIQUE INDEX "UQ_usuario_dni" ON usuario(dni)
;

-- 
-- INDEX: "UQ_ciudad_id_externo_y_api" 
--

CREATE UNIQUE INDEX "UQ_ciudad_id_externo_y_api" ON ciudad(id_externo, fuente_api)
;
-- 
-- INDEX: "UQ_provincia_id_externo_y_api" 
--

CREATE UNIQUE INDEX "UQ_provincia_id_externo_y_api" ON provincia(id_externo, fuente_api)
;

-- 
-- TABLE: actividad 
--

ALTER TABLE actividad ADD CONSTRAINT "Refplanificacion171" 
    FOREIGN KEY (id_planificacion)
    REFERENCES planificacion(id_planificacion)
;

ALTER TABLE actividad ADD CONSTRAINT "Refubicacion991" 
    FOREIGN KEY (id_ubicacion)
    REFERENCES ubicacion(id_ubicacion)
;


-- 
-- TABLE: agenda 
--

ALTER TABLE agenda ADD CONSTRAINT "Refusuario1461" 
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
;


-- 
-- TABLE: asignacion_actividad 
--

ALTER TABLE asignacion_actividad ADD CONSTRAINT "Refmiembros_proyecto961" 
    FOREIGN KEY (id_miembro)
    REFERENCES miembros_proyecto(id_miembro)
;

ALTER TABLE asignacion_actividad ADD CONSTRAINT "Refactividad971" 
    FOREIGN KEY (id_actividad)
    REFERENCES actividad(id_actividad)
;


-- 
-- TABLE: auditoria 
--

ALTER TABLE auditoria ADD CONSTRAINT "Reftipo_accion_auditoria1601" 
    FOREIGN KEY (id_tipo_auditoria)
    REFERENCES tipo_accion_auditoria(id_tipo_auditoria)
;

ALTER TABLE auditoria ADD CONSTRAINT "Refusuario1621" 
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
;


-- 
-- TABLE: bloqueo_agenda 
--

ALTER TABLE bloqueo_agenda ADD CONSTRAINT "Refagenda1441" 
    FOREIGN KEY (id_agenda)
    REFERENCES agenda(id_agenda)
;


-- 
-- TABLE: caracteristica_perfil 
--

ALTER TABLE caracteristica_perfil ADD CONSTRAINT "Refperfil91" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE caracteristica_perfil ADD CONSTRAINT "Refvalor_caracteristica1641" 
    FOREIGN KEY (id_valor, id_caracteristica)
    REFERENCES valor_caracteristica(id_valor, id_caracteristica)
;

ALTER TABLE caracteristica_perfil ADD CONSTRAINT "Refcaracteristica_tecnica1661" 
    FOREIGN KEY (id_caracteristica)
    REFERENCES caracteristica_tecnica(id_caracteristica)
;


-- 
-- TABLE: caracteristica_tecnica 
--

ALTER TABLE caracteristica_tecnica ADD CONSTRAINT "Refprofesion131" 
    FOREIGN KEY (id_profesion)
    REFERENCES profesion(id_profesion)
;

ALTER TABLE caracteristica_tecnica ADD CONSTRAINT "Refunidad_medida1631" 
    FOREIGN KEY (id_unidad)
    REFERENCES unidad_medida(id_unidad)
;


-- 
-- TABLE: ciudad 
--

ALTER TABLE ciudad ADD CONSTRAINT "Refprovincia1901" 
    FOREIGN KEY (id_provincia)
    REFERENCES provincia(id_provincia)
;


-- 
-- TABLE: colaborador_publicacion 
--

ALTER TABLE colaborador_publicacion ADD CONSTRAINT "Refpublicacion931" 
    FOREIGN KEY (id_publicacion)
    REFERENCES publicacion(id_publicacion)
;

ALTER TABLE colaborador_publicacion ADD CONSTRAINT "Refperfil941" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;


-- 
-- TABLE: comentario 
--

ALTER TABLE comentario ADD CONSTRAINT "Refpublicacion721" 
    FOREIGN KEY (id_publicacion)
    REFERENCES publicacion(id_publicacion)
;

ALTER TABLE comentario ADD CONSTRAINT "Refperfil831" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;


-- 
-- TABLE: dependencia_actividades 
--

ALTER TABLE dependencia_actividades ADD CONSTRAINT "Refactividad201" 
    FOREIGN KEY (id_actividad_predecesora)
    REFERENCES actividad(id_actividad)
;

ALTER TABLE dependencia_actividades ADD CONSTRAINT "Refactividad221" 
    FOREIGN KEY (id_actividad_sucesora)
    REFERENCES actividad(id_actividad)
;


-- 
-- TABLE: detalle_auditoria 
--

ALTER TABLE detalle_auditoria ADD CONSTRAINT "Refauditoria1611" 
    FOREIGN KEY (id_auditoria)
    REFERENCES auditoria(id_auditoria)
;


-- 
-- TABLE: habilidad_perfil 
--

ALTER TABLE habilidad_perfil ADD CONSTRAINT "Refperfil102" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE habilidad_perfil ADD CONSTRAINT "Refhabilidad1541" 
    FOREIGN KEY (id_habilidad)
    REFERENCES habilidad(id_habilidad)
;


-- 
-- TABLE: hito 
--

ALTER TABLE hito ADD CONSTRAINT "Refproyecto1521" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;


-- 
-- TABLE: hito_actividad 
--

ALTER TABLE hito_actividad ADD CONSTRAINT "Refhito1501" 
    FOREIGN KEY (id_hito)
    REFERENCES hito(id_hito)
;

ALTER TABLE hito_actividad ADD CONSTRAINT "Refactividad1511" 
    FOREIGN KEY (id_actividad)
    REFERENCES actividad(id_actividad)
;


-- 
-- TABLE: imagen_moodboard 
--

ALTER TABLE imagen_moodboard ADD CONSTRAINT "Refimagen791" 
    FOREIGN KEY (id_imagen)
    REFERENCES imagen(id_imagen)
;

ALTER TABLE imagen_moodboard ADD CONSTRAINT "Refmoodboard801" 
    FOREIGN KEY (id_moodboard)
    REFERENCES moodboard(id_moodboard)
;


-- 
-- TABLE: imagen_publicacion 
--

ALTER TABLE imagen_publicacion ADD CONSTRAINT "Refimagen771" 
    FOREIGN KEY (id_imagen)
    REFERENCES imagen(id_imagen)
;

ALTER TABLE imagen_publicacion ADD CONSTRAINT "Refpublicacion781" 
    FOREIGN KEY (id_publicacion)
    REFERENCES publicacion(id_publicacion)
;


-- 
-- TABLE: invitacion_actividad 
--

ALTER TABLE invitacion_actividad ADD CONSTRAINT "Refperfil1011" 
    FOREIGN KEY (id_perfil_remitente)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE invitacion_actividad ADD CONSTRAINT "Refrequerimiento_actividad1021" 
    FOREIGN KEY (id_requerimiento_act)
    REFERENCES requerimiento_actividad(id_requerimiento_act)
;

ALTER TABLE invitacion_actividad ADD CONSTRAINT "Refperfil1031" 
    FOREIGN KEY (id_perfil_destinatario)
    REFERENCES perfil(id_perfil)
;


-- 
-- TABLE: invitacion_gral 
--

ALTER TABLE invitacion_gral ADD CONSTRAINT "Refperfil1251" 
    FOREIGN KEY (id_perfil_destinatario)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE invitacion_gral ADD CONSTRAINT "Refperfil1261" 
    FOREIGN KEY (id_perfil_remitente)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE invitacion_gral ADD CONSTRAINT "Refrequerimiento_gral_proyecto1271" 
    FOREIGN KEY (id_requerimiento_gral)
    REFERENCES requerimiento_gral_proyecto(id_requerimiento_gral)
;


-- 
-- TABLE: jornada_agenda 
--

ALTER TABLE jornada_agenda ADD CONSTRAINT "Refagenda1451" 
    FOREIGN KEY (id_agenda)
    REFERENCES agenda(id_agenda)
;


-- 
-- TABLE: me_gusta 
--

ALTER TABLE me_gusta ADD CONSTRAINT "Refperfil821" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE me_gusta ADD CONSTRAINT "Refpublicacion861" 
    FOREIGN KEY (id_publicacion)
    REFERENCES publicacion(id_publicacion)
;


-- 
-- TABLE: miembros_proyecto 
--

ALTER TABLE miembros_proyecto ADD CONSTRAINT "Refperfil581" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE miembros_proyecto ADD CONSTRAINT "Refrol_proyecto1091" 
    FOREIGN KEY (id_rol_proyecto)
    REFERENCES rol_proyecto(id_rol_proyecto)
;

ALTER TABLE miembros_proyecto ADD CONSTRAINT "Refperfil_tyc1841" 
    FOREIGN KEY (id_perfil, id_tyc_aceptado)
    REFERENCES perfil_tyc(id_perfil, id_tyc)
;

ALTER TABLE miembros_proyecto ADD CONSTRAINT "Refproyecto51" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;


-- 
-- TABLE: moodboard 
--

ALTER TABLE moodboard ADD CONSTRAINT "Refproyecto731" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;


-- 
-- TABLE: notificacion 
--

ALTER TABLE notificacion ADD CONSTRAINT "Refusuario1531" 
    FOREIGN KEY (id_usuario_destino)
    REFERENCES usuario(id_usuario)
;


-- 
-- TABLE: objetivo 
--

ALTER TABLE objetivo ADD CONSTRAINT "Refproyecto651" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;


-- 
-- TABLE: perfil 
--

ALTER TABLE perfil ADD CONSTRAINT "Refprofesion951" 
    FOREIGN KEY (id_profesion)
    REFERENCES profesion(id_profesion)
;

ALTER TABLE perfil ADD CONSTRAINT "Refimagen1291" 
    FOREIGN KEY (foto_perfil)
    REFERENCES imagen(id_imagen)
;

ALTER TABLE perfil ADD CONSTRAINT "Refusuario1571" 
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
;


-- 
-- TABLE: perfil_tyc 
--

ALTER TABLE perfil_tyc ADD CONSTRAINT "Refperfil1811" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;


-- 
-- TABLE: planificacion 
--

ALTER TABLE planificacion ADD CONSTRAINT "Refproyecto161" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;


-- 
-- TABLE: postulacion_actividad 
--

ALTER TABLE postulacion_actividad ADD CONSTRAINT "Refperfil601" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE postulacion_actividad ADD CONSTRAINT "Refrequerimiento_actividad641" 
    FOREIGN KEY (id_requerimiento_act)
    REFERENCES requerimiento_actividad(id_requerimiento_act)
;


-- 
-- TABLE: postulacion_gral 
--

ALTER TABLE postulacion_gral ADD CONSTRAINT "Refperfil1231" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE postulacion_gral ADD CONSTRAINT "Refrequerimiento_gral_proyecto1241" 
    FOREIGN KEY (id_requerimiento_gral)
    REFERENCES requerimiento_gral_proyecto(id_requerimiento_gral)
;


-- 
-- TABLE: provincia 
--

ALTER TABLE provincia ADD CONSTRAINT "Refpais1891" 
    FOREIGN KEY (id_pais)
    REFERENCES pais(id_pais)
;


-- 
-- TABLE: proyecto 
--

ALTER TABLE proyecto ADD CONSTRAINT "Refubicacion1301" 
    FOREIGN KEY (id_ubicacion)
    REFERENCES ubicacion(id_ubicacion)
;


-- 
-- TABLE: publicacion 
--

ALTER TABLE publicacion ADD CONSTRAINT "Refperfil841" 
    FOREIGN KEY (id_perfil)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE publicacion ADD CONSTRAINT "Refproyecto1581" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;


-- 
-- TABLE: requerimiento_act_caract 
--

ALTER TABLE requerimiento_act_caract ADD CONSTRAINT "Refrequerimiento_actividad291" 
    FOREIGN KEY (id_requerimiento_act)
    REFERENCES requerimiento_actividad(id_requerimiento_act)
;

ALTER TABLE requerimiento_act_caract ADD CONSTRAINT "Refcaracteristica_tecnica1731" 
    FOREIGN KEY (id_caracteristica)
    REFERENCES caracteristica_tecnica(id_caracteristica)
;


-- 
-- TABLE: requerimiento_act_caract_valor 
--

ALTER TABLE requerimiento_act_caract_valor ADD CONSTRAINT "Refrequerimiento_act_caract1741" 
    FOREIGN KEY (id_req_act_caract)
    REFERENCES requerimiento_act_caract(id_req_act_caract)
;

ALTER TABLE requerimiento_act_caract_valor ADD CONSTRAINT "Refvalor_caracteristica1751" 
    FOREIGN KEY (id_valor, id_caracteristica)
    REFERENCES valor_caracteristica(id_valor, id_caracteristica)
;


-- 
-- TABLE: requerimiento_act_habilidad 
--

ALTER TABLE requerimiento_act_habilidad ADD CONSTRAINT "Refrequerimiento_actividad301" 
    FOREIGN KEY (id_requerimiento_act)
    REFERENCES requerimiento_actividad(id_requerimiento_act)
;

ALTER TABLE requerimiento_act_habilidad ADD CONSTRAINT "Refhabilidad331" 
    FOREIGN KEY (id_habilidad)
    REFERENCES habilidad(id_habilidad)
;


-- 
-- TABLE: requerimiento_actividad 
--

ALTER TABLE requerimiento_actividad ADD CONSTRAINT "Refprofesion661" 
    FOREIGN KEY (id_profesion)
    REFERENCES profesion(id_profesion)
;

ALTER TABLE requerimiento_actividad ADD CONSTRAINT "Refactividad681" 
    FOREIGN KEY (id_actividad)
    REFERENCES actividad(id_actividad)
;


-- 
-- TABLE: requerimiento_gral_caract 
--

ALTER TABLE requerimiento_gral_caract ADD CONSTRAINT "Refrequerimiento_gral_proyecto1761" 
    FOREIGN KEY (id_requerimiento_gral)
    REFERENCES requerimiento_gral_proyecto(id_requerimiento_gral)
;

ALTER TABLE requerimiento_gral_caract ADD CONSTRAINT "Refcaracteristica_tecnica1791" 
    FOREIGN KEY (id_caracteristica)
    REFERENCES caracteristica_tecnica(id_caracteristica)
;


-- 
-- TABLE: requerimiento_gral_caract_valor 
--

ALTER TABLE requerimiento_gral_caract_valor ADD CONSTRAINT "Refvalor_caracteristica1771" 
    FOREIGN KEY (id_valor, id_caracteristica)
    REFERENCES valor_caracteristica(id_valor, id_caracteristica)
;

ALTER TABLE requerimiento_gral_caract_valor ADD CONSTRAINT "Refrequerimiento_gral_caract1781" 
    FOREIGN KEY (id_req_gral_caract)
    REFERENCES requerimiento_gral_caract(id_req_gral_caract)
;


-- 
-- TABLE: requerimiento_gral_habilidad 
--

ALTER TABLE requerimiento_gral_habilidad ADD CONSTRAINT "Refrequerimiento_gral_proyecto1171" 
    FOREIGN KEY (id_requerimiento_gral)
    REFERENCES requerimiento_gral_proyecto(id_requerimiento_gral)
;

ALTER TABLE requerimiento_gral_habilidad ADD CONSTRAINT "Refhabilidad1191" 
    FOREIGN KEY (id_habilidad)
    REFERENCES habilidad(id_habilidad)
;


-- 
-- TABLE: requerimiento_gral_proyecto 
--

ALTER TABLE requerimiento_gral_proyecto ADD CONSTRAINT "Refproyecto1131" 
    FOREIGN KEY (id_proyecto)
    REFERENCES proyecto(id_proyecto)
;

ALTER TABLE requerimiento_gral_proyecto ADD CONSTRAINT "Refprofesion1141" 
    FOREIGN KEY (id_profesion)
    REFERENCES profesion(id_profesion)
;


-- 
-- TABLE: rol_global_permiso 
--

ALTER TABLE rol_global_permiso ADD CONSTRAINT "Refrol_global1851" 
    FOREIGN KEY (id_rol_global)
    REFERENCES rol_global(id_rol_global)
;

ALTER TABLE rol_global_permiso ADD CONSTRAINT "Refpermiso_global1861" 
    FOREIGN KEY (id_permiso_global)
    REFERENCES permiso_global(id_permiso_global)
;


-- 
-- TABLE: rol_proyecto_permiso 
--

ALTER TABLE rol_proyecto_permiso ADD CONSTRAINT "Refrol_proyecto1871" 
    FOREIGN KEY (id_rol_proyecto)
    REFERENCES rol_proyecto(id_rol_proyecto)
;

ALTER TABLE rol_proyecto_permiso ADD CONSTRAINT "Refpermiso_proyecto1881" 
    FOREIGN KEY (id_permiso_proyecto)
    REFERENCES permiso_proyecto(id_permiso_proyecto)
;


-- 
-- TABLE: solicitud_colaboracion 
--

ALTER TABLE solicitud_colaboracion ADD CONSTRAINT "Refpublicacion871" 
    FOREIGN KEY (id_publicacion)
    REFERENCES publicacion(id_publicacion)
;

ALTER TABLE solicitud_colaboracion ADD CONSTRAINT "Refperfil881" 
    FOREIGN KEY (id_perfil_remitente)
    REFERENCES perfil(id_perfil)
;

ALTER TABLE solicitud_colaboracion ADD CONSTRAINT "Refperfil901" 
    FOREIGN KEY (id_perfil_destinatario)
    REFERENCES perfil(id_perfil)
;


-- 
-- TABLE: ubicacion 
--

ALTER TABLE ubicacion ADD CONSTRAINT "Refciudad1911" 
    FOREIGN KEY (id_ciudad)
    REFERENCES ciudad(id_ciudad)
;


-- 
-- TABLE: usuario 
--

ALTER TABLE usuario ADD CONSTRAINT "Refgenero1401" 
    FOREIGN KEY (id_genero)
    REFERENCES genero(id_genero)
;

ALTER TABLE usuario ADD CONSTRAINT "Refrol_global1411" 
    FOREIGN KEY (id_rol_global)
    REFERENCES rol_global(id_rol_global)
;

ALTER TABLE usuario ADD CONSTRAINT "Refubicacion1431" 
    FOREIGN KEY (id_ubicacion)
    REFERENCES ubicacion(id_ubicacion)
;


-- 
-- TABLE: valor_caracteristica 
--

ALTER TABLE valor_caracteristica ADD CONSTRAINT "Refcaracteristica_tecnica1721" 
    FOREIGN KEY (id_caracteristica)
    REFERENCES caracteristica_tecnica(id_caracteristica)
;



-- ============================================================================
-- CARGA DE SEMILLAS (SEEDS)
-- (Ejecutadas tras la creación de todas las tablas e índices)
-- ============================================================================

INSERT INTO tipo_accion_auditoria (id_tipo_auditoria, nombre) VALUES
    (1, 'INSERT'),
    (2, 'UPDATE'),
    (3, 'DELETE'),
    (4, 'LOGIN'),
    (5, 'LOGOUT')
ON CONFLICT (id_tipo_auditoria) DO UPDATE 
    SET nombre = EXCLUDED.nombre;

INSERT INTO configuracion_sistema (clave, valor, descripcion) VALUES
    ('SCHEDULER_DESHABILITACION_HORA',   '2',           'Hora del dia (0-23) en la que se ejecuta el scheduler de deshabilitacion'),
    ('SCHEDULER_DESHABILITACION_MINUTO', '0',           'Minuto (0-59) en el que se ejecuta el scheduler de deshabilitacion'),
    ('SCHEDULER_DESHABILITACION_CRON',   '0 0 2 * * *', 'Expresion cron para el scheduler de deshabilitacion de usuarios'),
    ('CATALOGO_GEOREF_PAIS_ISO',        'AR',          'Codigo ISO del pais para georeferenciacion de ubicaciones con API Georef')

ON CONFLICT (clave) DO UPDATE 
    SET valor       = EXCLUDED.valor,
        descripcion = EXCLUDED.descripcion;

INSERT INTO genero (id_genero, codigo, nombre) VALUES
    (1, 'MUJER',      'Mujer'),
    (2, 'HOMBRE',     'Hombre'),
    (3, 'NO_BINARIO', 'No binario'),
    (4, 'NO_DECIRLO', 'Prefiero no decirlo')
ON CONFLICT (id_genero) DO UPDATE 
    SET codigo = EXCLUDED.codigo,
        nombre = EXCLUDED.nombre;

INSERT INTO pais (id_pais, codigo_iso, nombre, activo) VALUES
    (1, 'AR', 'Argentina', true)
ON CONFLICT (id_pais) DO UPDATE 
    SET codigo_iso = EXCLUDED.codigo_iso,
        nombre     = EXCLUDED.nombre,
        activo     = EXCLUDED.activo;

INSERT INTO habilidad (id_habilidad, codigo, nombre, descripcion) VALUES
    (1,  'FOTO_ESTUDIO',        'Fotografía de Estudio',      'Manejo experto de iluminación y sets fotográficos en interiores.'),
    (2,  'FOTO_EXTERIOR',       'Fotografía en Exteriores',   'Dominio de luz natural y encuadres en locaciones abiertas.'),
    (3,  'EDICION_DIGITAL',     'Retoque y Edición Digital',  'Postproducción digital y corrección cromática avanzada.'),
    (4,  'PASARELA',            'Desfile en Pasarela',        'Dominio de ritmo, postura y modelaje en vivo.'),
    (5,  'MODELAJE_EDITORIAL', 'Modelaje Editorial',         'Capacidad de expresión visual para revistas y catálogos de moda.'),
    (6,  'MAQUILLAJE_HD',       'Maquillaje Audiovisual/HD',  'Técnicas de maquillaje aptas para cámaras de alta definición.'),
    (7,  'MAQUILLAJE_ARTISTICO','Maquillaje Artístico',       'Caracterización, fantasía y efectos visuales de maquillaje.'),
    (8,  'CORTE_CONFECCION',    'Corte y Confección',         'Habilidad de patronaje y armado artesanal de prendas.'),
    (9,  'PEINADO_EDITORIAL',   'Peinado Editorial',          'Creación de peinados estructurados para producciones de moda.'),
    (10,  'MAQUILLAJE_FX',   'Maquillaje de efectos especiales (FX)',          'Técnicas de maquillaje para simular heridas, envejecimiento, transformaciones en la piel, entre otros')
ON CONFLICT (id_habilidad) DO UPDATE 
    SET codigo      = EXCLUDED.codigo,
        nombre      = EXCLUDED.nombre,
        descripcion = EXCLUDED.descripcion;

INSERT INTO permiso_global (id_permiso_global, nombre) VALUES
    (1, 'VER_USUARIOS'),
    (2, 'HABILITAR_USUARIO'),
    (3, 'DESHABILITAR_USUARIO'),
    (4, 'VER_CARACTERISTICAS'),
    (5, 'CREAR_CARACTERISTICA'),
    (6, 'MODIFICAR_CARACTERISTICA'),
    (7, 'ELIMINAR_CARACTERISTICA'),
    (8, 'ADMINISTRAR_CONFIGURACION')
ON CONFLICT (id_permiso_global) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO permiso_proyecto (id_permiso_proyecto, nombre) VALUES
    (1,  'VER_PROYECTO'),
    (2,  'MODIFICAR_PROYECTO'),
    (3,  'PUBLICAR_PROYECTO'),
    (4,  'CONFIRMAR_PROYECTO'),
    (5,  'FINALIZAR_PROYECTO'),
    (6,  'CANCELAR_PROYECTO'),
    (7,  'CREAR_ACTIVIDAD'),
    (8,  'MODIFICAR_ACTIVIDAD'),
    (9,  'ELIMINAR_ACTIVIDAD'),
    (10, 'ASIGNAR_ACTIVIDAD'),
    (11, 'GESTIONAR_POSTULACIONES'),
    (12, 'INVITAR_MIEMBRO'),
    (13, 'ELIMINAR_INVITACION'),
    (14, 'ELIMINAR_INTEGRANTE')
ON CONFLICT (id_permiso_proyecto) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO rol_global (id_rol_global, nombre, codigo) VALUES
    (1, 'Administrador', 'ADMINISTRADOR'),
    (2, 'Usuario', 'USUARIO')
ON CONFLICT (id_rol_global) DO UPDATE
	SET nombre = EXCLUDED.nombre,
		codigo = EXCLUDED.codigo;

INSERT INTO rol_global_permiso (id_rol_global, id_permiso_global)
SELECT rg.id_rol_global, pg.id_permiso_global
FROM rol_global rg
CROSS JOIN permiso_global pg
WHERE rg.nombre = 'Administrador'
ON CONFLICT (id_rol_global, id_permiso_global) DO NOTHING;

INSERT INTO rol_proyecto (id_rol_proyecto, codigo, nombre) VALUES
    (1, 'DIRECTOR', 'Director de proyecto'),
    (2, 'MIEMBRO', 'Miembro de proyecto')
ON CONFLICT (id_rol_proyecto) DO UPDATE
	SET codigo = EXCLUDED.codigo,
		nombre = EXCLUDED.nombre;

INSERT INTO rol_proyecto_permiso (id_rol_proyecto, id_permiso_proyecto)
SELECT rp.id_rol_proyecto, pp.id_permiso_proyecto
FROM rol_proyecto rp
CROSS JOIN permiso_proyecto pp
WHERE rp.codigo = 'DIRECTOR'
ON CONFLICT (id_rol_proyecto, id_permiso_proyecto) DO NOTHING;

INSERT INTO rol_proyecto_permiso (id_rol_proyecto, id_permiso_proyecto)
SELECT rp.id_rol_proyecto, pp.id_permiso_proyecto
FROM rol_proyecto rp
JOIN permiso_proyecto pp ON pp.nombre IN ('VER_PROYECTO')
WHERE rp.codigo = 'MIEMBRO'
ON CONFLICT (id_rol_proyecto, id_permiso_proyecto) DO NOTHING;

INSERT INTO unidad_medida (id_unidad, nombre, simbolo, tipo_dato_permitido) VALUES
    (1, 'Centímetro', 'cm',    'NUMERICO'),
    (2, 'Metro',      'm',     'NUMERICO'),
    (3, 'Pulgada',    'in',    'NUMERICO'),
    (4, 'Kilogramo',  'kg',    'NUMERICO')
ON CONFLICT (id_unidad) DO UPDATE 
    SET nombre              = EXCLUDED.nombre,
        simbolo             = EXCLUDED.simbolo,
        tipo_dato_permitido = EXCLUDED.tipo_dato_permitido;

INSERT INTO profesion (id_profesion, codigo, nombre, descripcion) VALUES
    (1, 'FOTOGRAFO',         'Fotógrafo',            'Profesional dedicado a la captura y edición de imágenes fotográficas.'),
    (2, 'MODELO',            'Modelo',               'Profesional que posa para producciones fotográficas, audiovisuales o pasarelas.'),
    (3, 'MAQUILLADOR',       'Maquillador',          'Especialista en estilismo facial, caracterización y técnicas de maquillaje.'),
    (4, 'DISENIADOR_MODA',   'Diseñador de Moda',    'Profesional dedicado a la creación, confección y diseño de indumentaria.'),
    (5, 'PRODUCTOR_MODA',    'Productor de Moda',    'Encargado de coordinar y organizar los recursos logísticos y visuales.'),
    (6, 'ESTILISTA_IMAGEN',  'Estilista de Imagen',  'Asesor responsable de definir la coherencia estilística e indumentaria.'),
    (7, 'ESTILISTA_CABELLO', 'Estilista de Cabello', 'Especialista en peinado, corte y tratamiento capilar para producciones.')
ON CONFLICT (id_profesion) DO UPDATE 
    SET codigo      = EXCLUDED.codigo,
        nombre      = EXCLUDED.nombre,
        descripcion = EXCLUDED.descripcion;

INSERT INTO caracteristica_tecnica (id_caracteristica, codigo, nombre, tipo_dato, id_unidad, id_profesion)
SELECT 
    v.id_caracteristica,
    v.codigo,
    v.nombre,
    v.tipo_dato,
    u.id_unidad,
    p.id_profesion
FROM (VALUES
    (1, 'ALTURA',         'Altura',             'NUMERICO',  'cm'),
    (2, 'MEDIDA_PECHO',   'Medida de Pecho',    'NUMERICO',  'cm'),
    (3, 'MEDIDA_CINTURA', 'Medida de Cintura',  'NUMERICO',  'cm'),
    (4, 'MEDIDA_CADERA',  'Medida de Cadera',   'NUMERICO',  'cm'),
    (5, 'COLOR_OJOS',     'Color de Ojos',      'ENUMERADO', 'color'),
    (6, 'COLOR_CABELLO',  'Color de Cabello',   'ENUMERADO', 'color'),
    (7, 'COLOR_PIEL',     'Tono de Piel',       'ENUMERADO', 'color'),
    (8, 'TIPO_CABELLO',   'Tipo de Cabello',    'ENUMERADO', NULL)
) AS v(id_caracteristica, codigo, nombre, tipo_dato, unidad_simbolo)
JOIN profesion p ON p.codigo = 'MODELO'
LEFT JOIN unidad_medida u ON u.simbolo = v.unidad_simbolo
ON CONFLICT (id_caracteristica) DO UPDATE 
    SET codigo       = EXCLUDED.codigo,
        nombre       = EXCLUDED.nombre,
        tipo_dato    = EXCLUDED.tipo_dato,
        id_unidad    = EXCLUDED.id_unidad,
        id_profesion = EXCLUDED.id_profesion;

-- Seeds para el catálogo de características de modelos
INSERT INTO valor_caracteristica (id_valor, id_caracteristica, etiqueta, color_hex)
SELECT v.id_valor, ct.id_caracteristica, v.etiqueta, v.color_hex
FROM (VALUES
    (1, 'Marrón',   '#6B4226'),
    (2, 'Negro',    '#1C1C1C'),
    (3, 'Azul',     '#3D85C6'),
    (4, 'Verde',    '#4E9A51'),
    (5, 'Avellana', '#A67B5B'),
    (6, 'Gris',     '#A9A9A9')
) AS v(id_valor, etiqueta, color_hex)
JOIN caracteristica_tecnica ct ON ct.codigo = 'COLOR_OJOS'
ON CONFLICT (id_valor, id_caracteristica) DO UPDATE 
    SET etiqueta  = EXCLUDED.etiqueta,
        color_hex = EXCLUDED.color_hex;

-- Valores para 'COLOR_CABELLO' (id_caracteristica = 6)
INSERT INTO valor_caracteristica (id_valor, id_caracteristica, etiqueta, color_hex)
SELECT v.id_valor, ct.id_caracteristica, v.etiqueta, v.color_hex
FROM (VALUES
    (1,  'Negro',     '#1C1C1C'),
    (2,  'Castaño',   '#4A2E1F'),
    (3,  'Rubio',     '#E8C267'),
    (4,  'Pelirrojo', '#B23A1E'),
    (5,  'Vino',      '#5F0000'),
    (6,  'Canoso',    '#C9C9C9'),
    (7,  'Verde',     '#519E35'),
    (8,  'Azul',      '#107AB3'),
    (9,  'Rosa',      '#FF33C2'),
    (10, 'Blanco',    '#FFFFFF'),
    (11, 'Violeta',   '#560080'),
    (12, 'Otro',      NULL)
) AS v(id_valor, etiqueta, color_hex)
JOIN caracteristica_tecnica ct ON ct.codigo = 'COLOR_CABELLO'
ON CONFLICT (id_valor, id_caracteristica) DO UPDATE 
    SET etiqueta  = EXCLUDED.etiqueta,
        color_hex = EXCLUDED.color_hex;

-- Valores para 'COLOR_PIEL' (id_caracteristica = 7)
INSERT INTO valor_caracteristica (id_valor, id_caracteristica, etiqueta, color_hex)
SELECT v.id_valor, ct.id_caracteristica, v.etiqueta, v.color_hex
FROM (VALUES
    (1, 'Muy clara',  '#F6D8C6'),
    (2, 'Clara',      '#EAC1A0'),
    (3, 'Media',      '#C68863'),
    (4, 'Morena',     '#8D5A3B'),
    (5, 'Oscura',     '#5C3A21'),
    (6, 'Muy oscura', '#3B2415')
) AS v(id_valor, etiqueta, color_hex)
JOIN caracteristica_tecnica ct ON ct.codigo = 'COLOR_PIEL'
ON CONFLICT (id_valor, id_caracteristica) DO UPDATE 
    SET etiqueta  = EXCLUDED.etiqueta,
        color_hex = EXCLUDED.color_hex;

-- Valores para 'TIPO_CABELLO' (id_caracteristica = 8)
INSERT INTO valor_caracteristica (id_valor, id_caracteristica, etiqueta, color_hex)
SELECT v.id_valor, ct.id_caracteristica, v.etiqueta, NULL
FROM (VALUES
    (1, 'Lacio'),
    (2, 'Ondulado'),
    (3, 'Rizado'),
    (4, 'Afro')
) AS v(id_valor, etiqueta)
JOIN caracteristica_tecnica ct ON ct.codigo = 'TIPO_CABELLO'
ON CONFLICT (id_valor, id_caracteristica) DO UPDATE 
    SET etiqueta  = EXCLUDED.etiqueta,
        color_hex = EXCLUDED.color_hex;

-- ============================================================================
-- Sincronización de secuencias post-seeds
-- (Asegura que los contadores de identidad continúen después del MAX(id) insertado en las semillas)
-- ============================================================================
SELECT setval(pg_get_serial_sequence('pais', 'id_pais'), COALESCE(MAX(id_pais), 1)) FROM pais;
SELECT setval(pg_get_serial_sequence('genero', 'id_genero'), COALESCE(MAX(id_genero), 1)) FROM genero;
SELECT setval(pg_get_serial_sequence('rol_global', 'id_rol_global'), COALESCE(MAX(id_rol_global), 1)) FROM rol_global;
SELECT setval(pg_get_serial_sequence('rol_proyecto', 'id_rol_proyecto'), COALESCE(MAX(id_rol_proyecto), 1)) FROM rol_proyecto;
SELECT setval(pg_get_serial_sequence('profesion', 'id_profesion'), COALESCE(MAX(id_profesion), 1)) FROM profesion;
SELECT setval(pg_get_serial_sequence('permiso_global', 'id_permiso_global'), COALESCE(MAX(id_permiso_global), 1)) FROM permiso_global;
SELECT setval(pg_get_serial_sequence('permiso_proyecto', 'id_permiso_proyecto'), COALESCE(MAX(id_permiso_proyecto), 1)) FROM permiso_proyecto;
SELECT setval(pg_get_serial_sequence('habilidad', 'id_habilidad'), COALESCE(MAX(id_habilidad), 1)) FROM habilidad;
SELECT setval(pg_get_serial_sequence('tipo_accion_auditoria', 'id_tipo_auditoria'), COALESCE(MAX(id_tipo_auditoria), 1)) FROM tipo_accion_auditoria;
SELECT setval(pg_get_serial_sequence('unidad_medida', 'id_unidad'), COALESCE(MAX(id_unidad), 1)) FROM unidad_medida;
SELECT setval(pg_get_serial_sequence('caracteristica_tecnica', 'id_caracteristica'), COALESCE(MAX(id_caracteristica), 1)) FROM caracteristica_tecnica;
SELECT setval(pg_get_serial_sequence('valor_caracteristica', 'id_valor'), COALESCE(MAX(id_valor), 1)) FROM valor_caracteristica;
