package org.mgroko.backend.repositorio;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;

import org.junit.jupiter.api.Test;
import org.mgroko.backend.admin.dto.AdminCaracteristicaTecnicaRequest;
import org.mgroko.backend.admin.dto.AdminValorCaracteristicaRequest;
import org.mgroko.backend.admin.servicio.AdminCaracteristicaTecnicaService;
import org.mgroko.backend.modelo.CaracteristicaTecnica;
import org.mgroko.backend.modelo.ValorCaracteristica;
import org.mgroko.backend.modelo.ValorCaracteristicaId;
import org.mgroko.backend.perfiles.dto.CaracteristicaTecnicaResponse;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

/**
 * Regresión del alta de valores de catálogo contra PostgreSQL real.
 *
 * La PK de {@code valor_caracteristica} es compuesta {@code (id_valor,
 * id_caracteristica)} y {@code id_valor} es {@code GENERATED BY DEFAULT AS
 * IDENTITY}. Hibernate solo autogenera esa parte si
 * {@link ValorCaracteristicaId#idValor} declara {@code @GeneratedValue};
 * sin la anotación enviaba {@code id_valor = NULL} y Postgres rechazaba el
 * INSERT con {@code DataIntegrityViolationException} (bug reportado en el
 * alta de características técnicas).
 */
@SpringBootTest
@Transactional
class ValorCaracteristicaRepositoryIntegrationTest extends AbstractPostgresIntegrationTest {

    @Autowired
    private ValorCaracteristicaRepository valorCaracteristicaRepository;

    @Autowired
    private CaracteristicaTecnicaRepository caracteristicaTecnicaRepository;

    @Autowired
    private ProfesionRepository profesionRepository;

    @Autowired
    private AdminCaracteristicaTecnicaService adminCaracteristicaTecnicaService;

    private Long idProfesionModelo() {
        return profesionRepository.buscar("%modelo%", "modelo").get(0).getIdProfesion();
    }

    private CaracteristicaTecnica caracteristicaEnumeradaSembrada() {
        return caracteristicaTecnicaRepository.buscar("%color_ojos%", "%", idProfesionModelo()).get(0);
    }

    @Test
    void guardar_conIdValorNulo_autogeneraElIdentificador() {
        CaracteristicaTecnica caracteristica = caracteristicaEnumeradaSembrada();

        ValorCaracteristica valor = ValorCaracteristica.builder()
                .id(new ValorCaracteristicaId(null, caracteristica.getIdCaracteristica()))
                .caracteristicaTecnica(caracteristica)
                .etiqueta("COLOR_PRUEBA_GENERACION")
                .colorHex("#123456")
                .build();

        ValorCaracteristica guardado = valorCaracteristicaRepository.saveAndFlush(valor);

        assertNotNull(guardado.getIdValor(), "id_valor debe autogenerarse (IDENTITY)");
        assertTrue(guardado.getIdValor() > 0);

        ValorCaracteristicaId clave = new ValorCaracteristicaId(
                guardado.getIdValor(), caracteristica.getIdCaracteristica());
        assertTrue(valorCaracteristicaRepository.findById(clave).isPresent(),
                "la fila debe poder leerse con la clave compuesta completa");
    }

    @Test
    void crearCaracteristica_conValoresIniciales_persisteLosValores() {
        AdminCaracteristicaTecnicaRequest request = new AdminCaracteristicaTecnicaRequest(
                "COLOR_TEST_GEN",
                "Color de prueba generación",
                null,
                idProfesionModelo(),
                "ENUMERADO",
                List.of(
                        new AdminValorCaracteristicaRequest(null, "ROJO_TEST", "#FF0000"),
                        new AdminValorCaracteristicaRequest(null, "AZUL_TEST", "#0000FF")));

        CaracteristicaTecnicaResponse creada = adminCaracteristicaTecnicaService.crear(request);

        assertNotNull(creada.idCaracteristica());
        List<ValorCaracteristica> valores =
                valorCaracteristicaRepository.findByCaracteristicaTecnica_IdCaracteristicaOrderByEtiqueta(
                        creada.idCaracteristica());

        assertEquals(2, valores.size(), "los valores iniciales deben persistirse");
        assertTrue(valores.stream().allMatch(v -> v.getIdValor() != null),
                "ningún valor debe quedar con id_valor NULL");
    }

    @Test
    void agregarValor_conIdValorNulo_autogeneraElIdentificador() {
        AdminValorCaracteristicaRequest request = new AdminValorCaracteristicaRequest(null, "VERDE_TEST", "#00FF00");

        var respuesta = adminCaracteristicaTecnicaService.agregarValor(
                caracteristicaEnumeradaSembrada().getIdCaracteristica(), request);

        assertNotNull(respuesta.idValor(), "respuesta del alta debe traer el id autogenerado");
    }
}
